### ISSUE TITLE
So... Is this still a thing?

### ISSUE THREAD

**Issue by henrypratt** [NextLevel/NextLevel#1]
I would really like a PBJVision library in swift, but I'm not sure if this is still active. If so, could you please provide documentation for installation as well as setting it up?

**Comment by piemonte** [comment]
it should be. we fell off our horses but will ride again soon.

**Comment by piemonte** [comment]
hey @henrypratt . the library is almost done, just working on a few aspects of video recording. may post some of the preliminary project early.
