### ISSUE TITLE
No sound when recording a video.

### ISSUE THREAD

**Issue by slash7** [NextLevel/NextLevel#10]
When recording a video the sound is not present.
Also, I saw you've used `.m4a` file extension for both video and audio.

**Comment by piemonte** [comment]
this should no longer be the case, please let me know otherwise.

**Comment by slash7** [comment]
hi @piemonte, I confirm that the file extension changed from `m4a` to `mp4` but the recorded video has no sound

**Comment by piemonte** [comment]
@slash7 apologies, just pushed/verified a fix 👍
