### ISSUE TITLE
Migrating to Swift 4 & xcode 9

### ISSUE THREAD

**Issue by olliem36** [NextLevel/NextLevel#101]
Hi, 

When migrating to swift4 and Xcode 9 I thought installing the latest pod would resolve compiler issues.  Aside from installing the latest pod (0.8.4) is there's further steps I need to take?

Example compile errors:

`/Pods/NextLevel/Sources/NextLevel+AVFoundation.swift:41:52: 'AVMediaType' (aka 'NSString') is not implicitly convertible to 'String!'; did you mean to use 'as' to explicitly convert?`

`/Pods/NextLevel/Sources/NextLevel+AVFoundation.swift:61:57: 'Any' is not convertible to 'AVCaptureInput.Port'`

Thanks in advance!

**Comment by piemonte** [comment]
hey @olliem36 i haven't encountered this specific issue. Swift 4 + Xcode 9 is what i'm using in my projects with `0.8.4`. will investigate if there's a particular config i'm missing.

**Comment by piemonte** [comment]
@olliem36 it looks like your target isn't specifying Swift 4. you should ensure that is being defined in your `Podfile`.

```
source 'git@github.com:cocoapods/Specs.git'

platform :ios, '11.0'

# setup
workspace './AppName.xcworkspace'
swift_version = '4.0'
use_frameworks!

target 'AppName' do
# ...
```

**Comment by frontier17** [comment]
I still have same problem

**Comment by piemonte** [comment]
hey @frontier17 – sorry to hear. those errors come up when the target swift is set to 3.X. check your build settings and make sure it's set to 4.0.

<img width="912" alt="screen shot 2017-10-03 at 12 06 37 am" src="https://user-images.githubusercontent.com/1870667/31113589-d8d25702-a7ce-11e7-9ff4-5306aa5e69d7.png">
