### ISSUE TITLE
Undefined symbols for architecture x86_64 on version 0.6.3

### ISSUE THREAD

**Issue by thexande** [NextLevel/NextLevel#102]
I am attempting to integrate version 0.6.3 into my swift 3.2 swift app. After adding it to my pod file, I am getting the following console output:

```
Undefined symbols for architecture x86_64:
  "__T0So22AVCapturePhotoSettingsC12AVFoundation01_abC16SwiftNativeTypesACWP", referenced from:
      __T09NextLevel0aB18PhotoConfigurationC19avcaptureDictionarys0F0VySSypGSgyF in NextLevelConfiguration.o
  "__T012AVFoundation39_AVCapturePhotoSettingsSwiftNativeTypesPAAE016availablePreviewc11PixelFormatG0SaySo8NSNumberCGfg", referenced from:
      __T09NextLevel0aB18PhotoConfigurationC19avcaptureDictionarys0F0VySSypGSgyF in NextLevelConfiguration.o
  "__T0So20AVCapturePhotoOutputC12AVFoundation01_abC16SwiftNativeTypesACWP", referenced from:
      __T09NextLevelAAC9flashModeAA0ab5FlashD0Ofs in NextLevel.o
  "__T012AVFoundation37_AVCapturePhotoOutputSwiftNativeTypesPAAE19supportedFlashModesSaySo8NSNumberCGfg", referenced from:
      __T09NextLevelAAC9flashModeAA0ab5FlashD0Ofs in NextLevel.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This issue was already reported with #99 , but I am using swift 3.2 still so I cannot upgrade past NextLevel 0.6.3. Any solutions?

**Comment by piemonte** [comment]
hey @thexande we can submit a 0.6.4 with the fix for 3.2. in the meantime, you can also update these lines locally or in a fork:

https://github.com/NextLevel/NextLevel/blob/master/Sources/NextLevel.swift#L1434-L1436
https://github.com/NextLevel/NextLevel/blob/24154a7852d3e4e5c1cee22a0f3937b1e3076511/Sources/NextLevelConfiguration.swift#L318-L320

**Comment by piemonte** [comment]
(or point to the swift-3.2 branch)

**Comment by thexande** [comment]
Solved! Thanks.
