### ISSUE TITLE
App rejected for using NextLevel (and not making use of NextLevel ARKit code)

### ISSUE THREAD

**Issue by captainuberawesome** [NextLevel/NextLevel#106]
App was rejected from App Store for violating point 4.2.1 of the App Store Review Guidelines

> 4.2.1 Apps should use APIs and frameworks for their intended purposes and indicate that integration in their app description. For example, the HomeKit framework should provide home automation services; and HealthKit should be used for health and fitness purposes and integrate with the Health app. Apps using ARKit should provide rich and integrated augmented reality experiences; merely dropping a model into an AR view or replaying animation is not enough.

The unused ARKit code from NextLevel was the reason for rejection. Maybe adding info that using this library without including ARKit functionality in your app will lead to app being rejected would be useful. As an alternative, splitting the library into two versions (with / without ARKit) would be great.

**Comment by piemonte** [comment]
@captainuberawesome oh man that's awful. sorry about this, will add preprocessing.

**Comment by piemonte** [comment]
122527b7afffc144618a20ed2ffbcec064af5bfa

**Comment by williamsthing** [comment]
@captainuberawesome Were you able to get your app accepted? I'm using NextLevel in my project and I'm aiming to get my app submitted and reviewed this weekend.

**Comment by captainuberawesome** [comment]
@williamsthing 

I've forked the repository and manually removed all ARKit references to have the app approved, but that was before this commit beee6cfa24ebd1f69db1a0d511c5be7a8b2e4053 was added. I'm pretty sure it fixes the problem and you will not have your app rejected.
