### ISSUE TITLE
Photo resolution issue

### ISSUE THREAD

**Issue by yasirmturk** [NextLevel/NextLevel#110]
Tried both photo and video mode and also tried the sample project.. but all of them provide data which makes a `UIImage` at max res {1080, 1920}, while the camera of iPhone is 12MP and it can provide me a photo of res {3000, 4000}, which is also the output of `UIImagePickerController`

I have explored but i am unable to find a configuration where i can set this option??

**Comment by piemonte** [comment]
commit fa752ecee0a9da7eacbce7e9c814fefdec17d0e3
Date:   Fri Feb 2 12:50:30 2018 -0800

    NextLevelPhotoConfiguration, add high resolution capture to settings, via @yasirmturk

**Comment by lschwe** [comment]
Not sure where it stopped working but im testing this on ios 12 and i cant capture a high quality photo unless i set `photoOutput.isHighResolutionCaptureEnabled = true` before

**Comment by piemonte** [comment]
5542d6b77b5b21fcfa83d3220ac8d888b63167b6
