### ISSUE TITLE
Preview orientation encounters issues

### ISSUE THREAD

**Issue by luispadron** [NextLevel/NextLevel#117]
I'm having issues with the rotation of the preview layer, it's happening super slowly and with a lot of stuttering.

My set up looks something like this:

```swift
self.nextLevel.delegate = self
self.nextLevel.videoDelegate = self
self.nextLevel.captureMode = .videoWithoutAudio
self.nextLevel.automaticallyUpdatesDeviceOrientation = true
self.nextLevel.videoConfiguration.preset = .hd1920x1080
```

I have the preview set up like this:

```swift
/// The recording preview which contains the next level recorder
private lazy var previewView: UIView = {
    let view = UIView(frame: UIScreen.main.bounds)
    view.backgroundColor = .black
    self.nextLevel.previewLayer.frame = view.bounds
    view.layer.addSublayer(self.nextLevel.previewLayer)
    return view
}()

// In view did load
self.previewView.frame = self.view.bounds
self.previewView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
self.view.insertSubview(self.previewView, at: 0)
```

Here is a GIF of the slow rotation:

![ezgif com-optimize](https://user-images.githubusercontent.com/13840545/34643359-0a709efa-f2f1-11e7-8de2-602bed524fd5.gif)

Any ideas what could be going on?

**Comment by lafalex** [comment]
@luispadron same problem, did you find a solution ?

**Comment by luispadron** [comment]
Yah, not use this library. It’s not much harder to just use the built in video features.

**Comment by hell3am** [comment]
@luispadron Did you find a good way to merge clips? The main reason I moved to this library was because I had issues with merging AVAssets.

**Comment by luispadron** [comment]
Never had a need to do that so no, sorry.

**Comment by kaifucious** [comment]
@piemonte was this bug ever fixed for Swift 4+? It's still showing up in the 4.0 branch.

**Comment by piemonte** [comment]
hey @kaifucious this hasn't been fixed yet

**Comment by andrewfashion** [comment]
Is this issue ever going to be fixed? @piemonte  thanks

**Comment by andrewfashion** [comment]
@luispadron Did you ever solve this issue?

**Comment by luispadron** [comment]
@andrewfashion as I mentioned above, I didn’t find a solution. I ended up writing my own simple player.

**Comment by Felix-Izarra-Bose** [comment]
This worked for me

`func nextLevel(_ nextLevel: NextLevel, didChangeDeviceOrientation deviceOrientation: NextLevelDeviceOrientation) {
        print("New orientation \(deviceOrientation.rawValue)")
        print("Bounds \(UIScreen.main.bounds)")
        if(deviceOrientation.rawValue == 4 || (screenChanged && deviceOrientation.rawValue == 1))
        {
            screenChanged = true
            self.previewView?.removeFromSuperview()
            
            self.previewView = UIView(frame: UIScreen.main.bounds)
            if let previewView = self.previewView {
                previewView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
                previewView.backgroundColor = UIColor.black
                NextLevel.shared.previewLayer.frame = previewView.bounds
                previewView.layer.addSublayer(NextLevel.shared.previewLayer)
                self.view.addSubview(previewView)
               
                
                self.view.sendSubviewToBack(previewView)
            }
        }

    }

`
