### ISSUE TITLE
Videos getting cut when merging or singular

### ISSUE THREAD

**Issue by theraad** [NextLevel/NextLevel#118]
Hi, 

I've been using NextLevel to record videos from the front cam. I've been facing some trouble as the videos are getting cut to around 5 seconds every time I record. I've confirmed that the video is being cut from the NextLevel completion as I was previously unsure whether it was from NextLevel or my conversion of the Video to data. 

A screenshot of my code to call retrieve the URL

![screen shot 2018-01-18 at 4 54 18 pm](https://user-images.githubusercontent.com/28601705/35104147-a7b70158-fc70-11e7-9ac9-b734153e774b.png)

Sorry for the very reduced code, but the VideoManager function i used just creates a path in the document directory to store the video, and moves the URL retrieved from NextLevel to that created path. I've tried this with the merged videos and the singular videos and i've had the same issue with both for some reason. 

Thank you, 
Alan

**Comment by piemonte** [comment]
thanks @theraad

**Comment by piemonte** [comment]
📎 https://github.com/NextLevel/NextLevel/issues/119
