### ISSUE TITLE
renderToCustomContextWithImageBuffer Never be called

### ISSUE THREAD

**Issue by haoking** [NextLevel/NextLevel#120]
No matter what I do, this method never be called.

let nextLevel = NextLevel.shared
        nextLevel.delegate = self
        nextLevel.deviceDelegate = self
        nextLevel.flashDelegate = self
        nextLevel.videoDelegate = self
        nextLevel.photoDelegate = self

        nextLevel.devicePosition = .front
        // video configuration
        nextLevel.videoConfiguration.bitRate = 2000000
        nextLevel.videoConfiguration.scalingMode = AVVideoScalingModeResizeAspectFill
        nextLevel.videoConfiguration.preset = .iFrame960x540
        nextLevel.videoConfiguration.maximumCaptureDuration = CMTimeMake(1, 15)
        nextLevel.isVideoCustomContextRenderingEnabled = true

**Comment by piemonte** [comment]
hey @haoking thanks for the issue. i'm using this method myself in a couple projects. have you tried setting a breakpoint and seeing why it doesn't reach?

**Comment by haoking** [comment]
Hi @piemonte Thanks for following this issue. I have reviewed the source code. I thought this method could be called only if a video is recording. I did not do that.
For now, I am facing a problem. I need to use OpenCV to deal with every FPS CMSampleBuffer in the method "willProcessRawVideoSampleBuffer", then show the resulting image on a UIImageView. As this method is from "AVCaptureVideoDataOutputSampleBufferDelegate". But this reduces the FPS from 30 FPS to 10 FPS. I have no idea about it. Please feel free to tell me some suggestions or some useful Framework. That will be very helpful. Thanks!

**Comment by piemonte** [comment]
hey @haoking no problem, thanks for the project interest. i wrote some code last year for better updating image views using the GPU instead of the CPU but i haven't had the chance to open source it. will try do so when i get the next free moment. (using either GL or metal)
