### ISSUE TITLE
Archiving error: No such module 'NextLevel'

### ISSUE THREAD

**Issue by tungfam** [NextLevel/NextLevel#122]
Hello,

First of all, thanks a lot for building such a great library! Appreciate it 👍 .

Run into building error while archiving the build.
Error: `No such module 'NextLevel'`
Specific requirement to reproduce: Set **deployment target** to **iOS 10**
Note: works fine for  **deployment target iOS 11**

Please see the screenshot below:
![image](https://user-images.githubusercontent.com/17186720/35707858-22e4a0d0-07b4-11e8-9ffd-c65767b4ee1f.png)

**Comment by piemonte** [comment]
hey @tungfam archiving the sample project's target app or target frame both succeed for me. the recommended installation for NextLevel is using Cocoapods.

**Comment by tungfam** [comment]
Thanks, @piemonte! Sorry for taking your time.

It was my bad, sorry for creating the issue. I haven't specified the platform in `Podfile`.

If someone runs to the same issue hope it will help:
![image](https://user-images.githubusercontent.com/17186720/35765755-3077e3fe-08d3-11e8-9e5a-e25a79f12d1c.png)

**Comment by piemonte** [comment]
@tungfam ah, that makes sense. not a problem, thanks for the interest in the project. ✌️
