### ISSUE TITLE
Camera orientation does not follow view orientation

### ISSUE THREAD

**Issue by yasirmturk** [NextLevel/NextLevel#124]
1. Make a view in fixed portrait mode
2. start camera while keeping device in landscape mode
3. weird preview is seen always rotated no matter how you rotate your device after that

i have tried using `automaticallyUpdatesDeviceOrientation` & `deviceOrientation` but it does not have any effect

**Comment by blurtime** [comment]
Encountered the same issue! There also seem to be some problems with the mirroringMode...

**Comment by piemonte** [comment]
📎 https://github.com/NextLevel/NextLevel/issues/117
