### ISSUE TITLE
availableVideoPixelFormatTypes on VideoSetting

### ISSUE THREAD

**Issue by haoking** [NextLevel/NextLevel#125]
Hi, @piemonte 
Hope everything good.
I find two bugs/problems in your project.
In the video setting, you use a lot of stable setting instead of open it to API.
1."self._videoOutput?.alwaysDiscardsLateVideoFrames = true" in be setted in "private func addVideoOutput()", but for my project I need to set it false. Also, openCV suggest to set it false. 'Cause lots of complex image process is much slower than 25FPS. SO It's better to set it false and set the CMTime at the same time. So I suggest to open this to an optional setting.

2.  another problem is "kCVPixelBufferPixelFormatTypeKey", in "private func addVideoOutput() -> Bool", what you do is to get the "availableVideoPixelFormatTypes" of system and use the best one. but when I work with openCV, there is a big issue which OpenCV is not support on "kCVPixelFormatType_420YpCbCr8BiPlanarFullRange" or "kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange" very well. OpenCV do a lot of good support just on "kCVPixelFormatType_32BGRA", as well as the Dlib library. So I think you can set a better one in default, but at least open it to optional setting on this.

At last, I think these two settings are also important and optional on original iOS SDK.
If you can fix that, I do not need to change a lot of things to your Lib on my project.
Lol.
Have a good one.

**Comment by piemonte** [comment]
hey @haoking thanks for the issue.

1) if you'd like to override some of the configuration properties, we can easily open those up. feel free to make a PR for this, that'd be great.

2) yes, in terms of processing planar range pixel buffer types, having a configuration to change the buffer type is also fine.

on a side note, you can convert planar buffers on the GPU to an rbg texture while still maintaining a good frame rate. that's what i'm doing with my projects and allows OpenCV use while still leaving the possibility to capture full range buffers for video. (you can do it with either metal or OpenGLES) it's a lot more work and i don't want to send you down a rabbit hole but it might be helpful to know.

here's a *partial* example of how processing can be done with GL. sorry, uses SceneKit, i have other versions that don't but don't have the time to open source right now. you might find it useful! 

📎 https://gist.github.com/piemonte/1c5e5a3f7fe70cdb312e2315fae1ad15
