### ISSUE TITLE
Tap to take photo, hold to record video

### ISSUE THREAD

**Issue by papipons** [NextLevel/NextLevel#126]
Hi! Good day! I have a problem which is switching between captureModes. 

My current approach is:
set captureMode to photo on button tap, before calling capturePhoto()
set captureMode to video on button hold (began), before calling record()
But it looks like changing modes takes some time and is asynchronous

I even tried creating a callback function that will be called on nextLevelCaptureModeDidChange
but there is a noticeable delay.

Is my requirement possible using this library? if yes, any idea how? 

Thanks

**Comment by piemonte** [comment]
hey @papipons thanks for the project interest. my recommendation is to always keep your app in video mode, and use the "capturePhotoFromVideo" method to use a still frame as an image.

this is what most apps do in order to avoid the delay in the hardware changing capture modes.

**Comment by papipons** [comment]
Wow! I never thought of that. Thank you very much for your useful response.

**Comment by Cez95** [comment]
hey @piemonte in which video delegate would you be able to access the image rendered upon button tap?

**Comment by piemonte** [comment]
hey @Cez95, this is the one after calling `capturePhotoFromVideo`:

```swift
    public func nextLevel(_ nextLevel: NextLevel, didCompletePhotoCaptureFromVideoFrame photoDict: [String : Any]?)
```
