### ISSUE TITLE
Swift 4.2 Release

### ISSUE THREAD

**Issue by dylanreich** [NextLevel/NextLevel#128]
Hi, I know it's early but NextLevel won't compile in Xcode 10 as Xcode is complaining about the specific version of Swift NextLevel was made in (appears to be Swift 4.1.2?). Xcode 10 seems to only have legacy support for Swift 3, Swift 4, and Swift 4.2. I might be misunderstanding Xcode but that's what appears to be the case. Let me know how I can help. Thanks!

**Comment by piemonte** [comment]
hey @dylanreich thanks for the issue. yep, i'll create a swift42 branch of NextLevel. i do this kinda lazily because swift can change itself a lot between each beta too.

NextLevel is currently versioned for swift 4.0.

**Comment by piemonte** [comment]
📎 https://github.com/NextLevel/NextLevel/tree/swift4.2

it needs a little love at the moment, several errors but will try do it sometime this weekend unless you want to open a PR

**Comment by dylanreich** [comment]
Cool! I forked it and updated from scratch. I opened up a PR: [https://github.com/NextLevel/NextLevel/pull/129]

**Comment by piemonte** [comment]
@dylanreich thanks again.

i mistakenly merged to master then had to do some clean up. brought your commits over to the 42 branch. should be good to go if you point your Podfile to 42. ✌️

**Comment by dylanreich** [comment]
No worries!!!
