### ISSUE TITLE
Still image capture doesn't work (previewPhotoSampleBuffer always nil)

### ISSUE THREAD

**Issue by graemesi** [NextLevel/NextLevel#13]
I'm trying to use NextLevel to capture a still photo. I've set `NextLevel.sharedInstance.cameraMode = .photo` and I'm calling `NextLevel.sharedInstance.capturePhoto()`

However, I noticed the `nextLevel(_:didProcessPhotoCaptureWith:photoConfiguration)` delegate method is never called. Looking at NextLevel.swift, I see that previewPhotoSampleBuffer is expected to to be non-nil.
```
public func capture(_ captureOutput: AVCapturePhotoOutput, didFinishProcessingPhotoSampleBuffer photoSampleBuffer: CMSampleBuffer?, previewPhotoSampleBuffer: CMSampleBuffer?, resolvedSettings: AVCaptureResolvedPhotoSettings, bracketSettings: AVCaptureBracketedStillImageSettings?, error: Error?) {
        if let sampleBuffer = photoSampleBuffer,
            let previewBuffer = previewPhotoSampleBuffer {
```
In my case previewPhotoSampleBuffer is always nil. Is there some configuration property that needs to be set to allow still photos to be taken? Thanks!

**Comment by piemonte** [comment]
hey @graemesi , apologies, that's a mistake on my part. the preview parameter just provides a thumbnail image of the photo taken – if it has been configured properly, which looks like i didn't do.

it should work if that check is removed or if a "preview" configuration is also added internally. i can look into it for you when i have a sec.

**Comment by piemonte** [comment]
@graemesi trunk should address your issue, let me know otherwise.

thanks for the feedback too, i've mostly been using/testing video capture.

**Comment by graemesi** [comment]
Excellent - thank you!
