### ISSUE TITLE
Enabling/Disabling Audio

### ISSUE THREAD

**Issue by neoncloth** [NextLevel/NextLevel#134]
Hey there,

Is there any way microphone input can be disabled and then re-enabled using this framework? I'm trying to create haptic feedback when the user taps on a button on the screen when the user is not recording. As playing haptics is disabled when an AVCaptureSession is active with an audio input, I'm thinking of disabling audio input while the user is not recording, and then enabling it just before they start recording.

Thanks for the help!

-William

**Comment by piemonte** [comment]
hey @williamsthing great idea, i've needed this as well.

**Comment by williamsthing** [comment]
Is there an ETA on this? Thanks!

**Comment by Kaspik** [comment]
Implemented and merged in! :)

**Comment by jeremyschoenherr** [comment]
amazing! i would love to use this as well. any idea when the next cocoapod release will happen? right now, i'm just swapping captureMode, and it's not all that performant :)

**Comment by piemonte** [comment]
`0.16.3` has been released

**Comment by naturalui** [comment]
@neoncloth did using this work for you to enable haptics?

I tried something like this on a buttonPress with no luck, it seems to reset the full capture.

@piemonte is there a way to mute audio temporary for these haptics?

```
    NextLevel.shared.disableAudioInputDevice()
    HapticFeedback.impact(.light).generate()
    NextLevel.shared.enableAudioInputDevice()
```

**Comment by neoncloth** [comment]
@naturalui I honestly can’t remember what I did but feel free to look over my awful code here:
https://github.com/flipwtf/app/blob/master/flip/Views/Camera%20View/FLCameraView.swift
