### ISSUE TITLE
iPhone  X camera capture

### ISSUE THREAD

**Issue by Hiren95** [NextLevel/NextLevel#136]
Hello there,

I have used NextLevel SDK and I got one issue while capturing photo from iPhone X camera

when I click the photo it  automatically zoom out the screen and I get different result for photo 
Please check attached images file.

![camera](https://user-images.githubusercontent.com/34739870/43203702-8e788c42-903c-11e8-84a6-b84852a8372b.jpg)
![result](https://user-images.githubusercontent.com/34739870/43203706-8ee0e8e6-903c-11e8-9baf-c5ef8b6ed8a3.jpg)

**Comment by piemonte** [comment]
hey @Hiren95, thanks for using NL. so the screen aspect ratio of iPhone X is different from the standard camera capture aspect ratios. these can be adjusted to whatever you design, but will involve clipping on older phones.

if you look at snap or insta you'll see they have black bars at the top and bottom of their captured iPhone X media.

**Comment by Hiren95** [comment]
okay, thank you @piemonte ... So how can I adjust camera for iPhone X...If I will give top/bottom space , will it work?
