### ISSUE TITLE
Recordings aren't complete on iPhone 6 and 7

### ISSUE THREAD

**Issue by rockar06** [NextLevel/NextLevel#137]
Hi everyone,

I'm facing an issue with this library, I follow the example in project to configure and start to record ([example code](https://github.com/NextLevel/NextLevel/blob/master/Project/NextLevel/CameraViewController.swift)).

My configuration is:

        let nextLevel = NextLevel.shared
        nextLevel.delegate = self
        nextLevel.videoDelegate = self
        
        // video configuration
        nextLevel.captureMode = .video
        nextLevel.videoConfiguration.preset = AVCaptureSession.Preset.hd1280x720
        nextLevel.videoConfiguration.bitRate = 2000000
        nextLevel.videoConfiguration.maxKeyFrameInterval = 30
        nextLevel.videoConfiguration.scalingMode = AVVideoScalingModeResizeAspectFill
        nextLevel.videoConfiguration.profileLevel = AVVideoProfileLevelH264HighAutoLevel
        nextLevel.devicePosition = .front
        
        // audio configuration
        nextLevel.audioConfiguration.bitRate = 44000

And my code to end recording is: 

```
func endCapture() {
        if let session = NextLevel.shared.session {
            if session.clips.count > 1 {
                session.mergeClips(usingPreset: AVAssetExportPresetHighestQuality, completionHandler: { (url: URL?, error: Error?) in
                    if let url = url {
                        let asset = AVAsset(url: url)
                        print("The duration of video is: \(CMTimeGetSeconds(asset.duration))")
                        self.saveVideo(withURL: url)
                    } else if let _ = error {
                        print("failed to merge clips at the end of capture \(String(describing: error))")
                    }
                })
            } else if let lastClipUrl = session.lastClipUrl {
                print("The duration of video is: \(CMTimeGetSeconds(asset.duration))")
                self.saveVideo(withURL: lastClipUrl)
            } else if session.currentClipHasStarted {
                session.endClip(completionHandler: { (clip, error) in
                    if error == nil {
                       print("The duration of video is: \(CMTimeGetSeconds((clip?.asset?.duration)!))")
                       self.saveVideo(withURL: (clip?.url)!)
                    } else {
                        print("failed to save clip at the end of capture \(String(describing: error))")
                    }
                })
            }
        }
    }
```

First, I tested in iPhone 8 Plus with 11.4.1 iOS version, and works perfect, it always record the exact time that I left recording.

But when I test in iPhone 6 or iPhone 7 with the same iOS version, the library always record a short video, for example if I record 30 seconds, NextLevel only record 5 seconds, it is always aleatory, I don't understand why only works well in iPhone 8 Plus.

Do you have any advice how to solve this problem?

**Comment by Rotemy** [comment]
I'm facing the same issue where `NextLevel.shared.record()` is stuck and the line after is not called. Only in iphone 6.

**Comment by piemonte** [comment]
thanks for reporting! this issue is being tracked here:

📎 https://github.com/NextLevel/NextLevel/issues/119

some solutions are discussed here:

📎 https://github.com/NextLevel/NextLevel/issues/62
