### ISSUE TITLE
Odd frame timing at 240fps

### ISSUE THREAD

**Issue by antonivanopoulos** [NextLevel/NextLevel#14]
Recording a video at 240fps on an iPhone 6, and I'm getting some strange video timing. Where I'd be expecting frame durations of 4.167ms, I'm getting alternating durations of 5ms and 3.33ms. Over the whole video the frame timings come out to a standard deviation of 0.8431996842ms (I've cut out the frames captured at the start because there's a bunch of frame loss that happens when the asset writer kicks in. But after that there's no real frame loss after having disabled the audio capture.)

You can see some of the data arond the frame timestamps I'm capturing here, https://docs.google.com/spreadsheets/d/1JTTQKT9yZA5_quej1LxAb4N0AsjdeZlvQUROS5IHFNc/edit?usp=sharing, was wondering if you had any ideas around where the offset might be coming from?

Thanks.

**Comment by piemonte** [comment]
hey @antonivanopoulos thanks for the feedback and data. i'll look into it next free chance i get.

if you notice any other behavior, let me know. we may have to increase the priority of the capture queue.

**Comment by antonivanopoulos** [comment]
Thanks for that @piemonte.

Quick follow up when you've got a chance, something I had forgotten about when I was tweaking some stuff, can you explain the following block? https://github.com/NextLevel/NextLevel/blob/master/Sources/NextLevel.swift#L2046

Was under the impression that it was trying to make sure the frames were of a minimum time apart, however it causes a lot of frame loss at 240fps, I ended up commenting it out temporarily which does fix that issue, but just wanted to wrap my head around what was going on there.

**Comment by piemonte** [comment]
Hey @antonivanopoulos thanks for the note. Apologies, haven't had a chance to get back to you. That delay was to allow slower devices to finish writing and closing the file on disk before starting a new one. i need to re-measure and/or possibly remove it.
