### ISSUE TITLE
Merging videos of different aspect ratios

### ISSUE THREAD

**Issue by alittle433** [NextLevel/NextLevel#141]
How would I preserve the aspect ratios of all of the clips when merging. For example I create a clip from an existing url with a square ratio and merge with a portrait recorded clip...it scales the square clip to fit the other video.

**Comment by piemonte** [comment]
hey @alittle433 thanks for the interest. you can use other libraries for managing transcoding changes.

📎 https://github.com/NextLevel/NextLevelSessionExporter

**Comment by alittle433** [comment]
Thank you, I will have a look at this.
