### ISSUE TITLE
Recording interrupted by didSkipAudioSampleBuffer(more frequent on zooms) 

### ISSUE THREAD

**Issue by Chepond** [NextLevel/NextLevel#145]
When I start record(), sometimes NextLevelVideoDelegate didSkipAudioSampleBuffer is called , and no matter how long I record, the video has actually stopped at the length at which didSkipAudioSampleBuffer is called. How can I avoid this happening, this happens more frequent when I'm zooming while recording. Thanks
Below is my code implementation:

override func viewDidLoad() {
        super.viewDidLoad()
        if let previewView = self.previewView {
            NextLevel.shared.previewLayer.frame = UIScreen.main.bounds
            previewView.layer.addSublayer(NextLevel.shared.previewLayer)
        }
    }
  override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        let nextLevel = NextLevel.shared
        if nextLevel.authorizationStatus(forMediaType: AVMediaType.video) == .authorized &&
            nextLevel.authorizationStatus(forMediaType: AVMediaType.audio) == .authorized {
            do {
            try nextLevel.start()
            nextLevel.delegate = self
            nextLevel.deviceDelegate = self
            nextLevel.videoDelegate = self
            nextLevel.photoDelegate = self

            nextLevel.videoConfiguration.maximumCaptureDuration = CMTimeMakeWithSeconds(120, 600)
            nextLevel.audioConfiguration.bitRate = 44000
            nextLevel.videoStabilizationMode = .auto
            nextLevel.mirroringMode = .auto
            nextLevel.videoConfiguration.bitRate = 20000000
            nextLevel.captureMode = .video
        } catch {
            print("NextLevel, failed to start camera session")
        }
        } else {
            nextLevel.requestAuthorization(forMediaType: AVMediaType.video)
            nextLevel.requestAuthorization(forMediaType: AVMediaType.audio)
        }
        
    }

    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        NextLevel.shared.stop()
    }

@objc func onHoldRecord(_ gestureRecognizer: UIGestureRecognizer) {
        let nextLevel = NextLevel.shared
        switch gestureRecognizer.state {
        case .began:
            if(nextLevel.isRecording) {
                return
            }
            nextLevel.record()
            self.panStartPoint = gestureRecognizer.location(in: self.view)
            self.panStartZoom = CGFloat(nextLevel.videoZoomFactor)
        case .changed:
            if isRecording {
                let newPoint = gestureRecognizer.location(in: self.view)
                let scale = (self.panStartPoint.y / newPoint.y)
                let newZoom = (scale * self.panStartZoom)
                nextLevel.videoZoomFactor = Float(newZoom)
            }
        case .ended:
            pauseRecord()
        case .failed:
            pauseRecord()
        case .cancelled:
            pauseRecord()
        default:
            break
        }
    }

**Comment by lalania** [comment]
I'm facing the same issue too

**Comment by damien-nd** [comment]
I do have a really close problem.

After like 7 frames, I get a delegate callback on didSkipVideoSampleBuffer (instead of audio).
It is always on first record, no problem if I stop and record an other video.

**Comment by piemonte** [comment]
hey everyon – thanks for this issue and information. ✌️ 

there was a serious bug that's now been resolved. if anything comes up related, please open a new issue.
