### ISSUE TITLE
Camera timing is off

### ISSUE THREAD

**Issue by lschwe** [NextLevel/NextLevel#148]
I followed this straight forward implementation https://github.com/NextLevel/NextLevel/issues/79 to make a custom photo camera.

When I do `self._nextLevel?.capturePhoto()`, the timing of the capture is a bit off/late, which can turn into a very frustrating experience for the user. 

Unfortunately, the photo camera becomes completely unusable when the flash is ON, because the camera cannot get the timing between the flash and photo capture correctly. 

Have you noticed this issue as well by any chance? I'm trying to look at the code and it doesnt seem like anything in particular is causing it. The only thing I can think of is it might have to do with needing to use AVCaptureStillImageOutput, but i doubt it...

**Comment by piemonte** [comment]
hey @lschwe i haven't noticed this but it could be the configuration, ie the size of the captured data and how it's being compressed.
