### ISSUE TITLE
Optional NextLevelDelegate methods?

### ISSUE THREAD

**Issue by bojanstef** [NextLevel/NextLevel#15]
Maybe everyone doesn't need to conform to every single method in `NextLevelDelegate`. We can think of more suitable names, I used [these comments as a guide](https://github.com/NextLevel/NextLevel/blob/master/Sources/NextLevel.swift#L418). Let me know what you think?

```Swift 
protocol NextLevelPermissionDelegate {}
protocol NextLevelConfigurationDelegate {}
protocol NextLevelSessionDelegate {}
protocol NextLevelDeviceModeOrientationDelegate {}
protocol NextLevelOrientationDelegate {}
protocol NextLevelApertureDelegate {}
protocol NextLevelFocusExposureWhiteBalanceDelegate {}
protocol NextLevelTorchFlashDelegate {}
protocol NextLevelZoomDelegate {}
protocol NextLevelPreviewDelegate {}
protocol NextLevelVideoProcessingDelegate {}
protocol NextLevelVideoRecordingSessionDelegate {}
protocol NextLevelVideoFramePhotoDelegate {}
protocol NextLevelPhotoDelegate {}
```

Inspired from: https://ashfurrow.com/blog/protocols-and-swift/

**Comment by piemonte** [comment]
@bojanstef nice idea 👌 allowing clients to create extensions for each of these areas is good too. 

Maybe not all of these categories but Video, Photo, Device, Session would be a good middle ground. what do you think?

**Comment by realq86** [comment]
Looks like this is not contained in the cocopod framework yet.

**Comment by piemonte** [comment]
thanks @realq86 we still have a couple more changes to make. you can point at master or just use the previous pod version until then.

**Comment by piemonte** [comment]
@bojanstef i've added a couple more delegates, i didn't want to go with as many, but we can add more in the future if really necessary. thanks again. ✌️

**Comment by bojanstef** [comment]
@piemonte Yup, I went a bit over the top. Your solution looks good to me :+1:
