### ISSUE TITLE
App rejection due to true depth api usage 

### ISSUE THREAD

**Issue by truemetal** [NextLevel/NextLevel#150]
Hi 

We've just had the app rejected with the note below. 
We don't use true depth in our project. I'm thinking about forking NextLevel repo and removing the references to APIs in question so that our app could pass the review.

Any better suggestions for this?
Thanks

-----

> Guideline 2.1 - Information Needed
> 
> 
> We have started the review of your app, but we are not able to continue because we need additional information about how your app uses information collected by the TrueDepth API.
> 
> Next Steps
> 
> To help us proceed with the review of your app, please provide complete and detailed information to the following questions.
> 
> • What information is your app collecting using the TrueDepth API?
> • For what purposes are you collecting this information? Please provide a complete and clear explanation of all planned uses of this data.
> • Will the data be shared with any third parties? Where will this information be stored?
> 
> Once you reply to this message in Resolution Center with the requested information, we can proceed with your review.

**Comment by baevra** [comment]
received the same rejection today

**Comment by truemetal** [comment]
Please check out #151 
Do you manually indent stuff, I wonder? I've noticed some stuff went sour after `Cmd+a` and `Ctrl+i`

Cheers

**Comment by piemonte** [comment]
will release a pod for this when i get some time. hopefully master is fine for you. also need to update the readme.

**Comment by piemonte** [comment]
thanks again! ✌️
