### ISSUE TITLE
Front facing camera not flipping video

### ISSUE THREAD

**Issue by patthehuman** [NextLevel/NextLevel#154]
I am using next level for recording video in my app.

When I set "mirroring" to ".auto" or ".on" I don't seem to get any effect.

Is there a proper way to flip the video preview layer as well as the content in the app?

Looking to emulate Snapchat/Instagram style of recording front facing and rear facing.

**Comment by blurtime** [comment]
#113

**Comment by piemonte** [comment]
thanks for the issue, closing dup since we have #113
