### ISSUE TITLE
how to use NextLevelSession class independently to record clips

### ISSUE THREAD

**Issue by omarojo** [NextLevel/NextLevel#159]
Im trying to use your NextLevelSession class independently to record clips. 
but when I try to initialize it, I get `'NextLevelSession' initializer is inaccessible due to 'internal' protection level`

Any idea how to use it? 
I dont wanna use your camera, I just want your samplebuffers recording capabilities. 

fyi: Im using cocoapods to access NextLevel

**Comment by piemonte** [comment]
hey @omarojo thanks for the project interest.

i hadn't been exposing that class but if you deem it useful stand-alone, it might be worth making it accessible.

so are you just doing all your own camera work and using the session/clips to manage edits?

**Comment by omarojo** [comment]
Exactly. Thing is Im working in an app that allows the user to either feed frames from Local Videos, Camera or Still Images, and interchange them at any time during the recording. I have my own classes that produce those frames in realtime.

What I currently do is feed these CMsamplebuffers into an assetwritter and works fine.

But now I want to implement VineStyle recording, and your class seem to handle that pretty well.  It may help me save ton of dev time, it manages the clips array, remove, add, merge, and calculate the correct timming offsets, which is awesome.

I could just copy paste your classes, but I prefer to keep it as a cocoapod so it’s always up to date and stuff :)

Btw great work !

**Comment by piemonte** [comment]
thanks much. pushed a couple changes to master. let me know if that works well.

**Comment by omarojo** [comment]
awesome, thanks. I will try it out. 
appreciated.

**Comment by omarojo** [comment]
Hey man.. can you make `NextLevelVideoConfiguration` and  `NextLevelAudioConfiguration` public too ? otherwise I cannot instantiate NextLevelSession.  😀

**Comment by piemonte** [comment]
no problem, thanks for catching that. should be good. 👍
