### ISSUE TITLE
Camera view not displaying properly in UIView

### ISSUE THREAD

**Issue by adxworld** [NextLevel/NextLevel#161]
I am trying to initialize the camera in a UIView connected through an IBOutlet but it seems to not fully adapt to the view. If the UIView is changed from an outlet to the container, It displays correctly. Following is the code  :

  `@IBOutlet var camcontainer: UIView!`
    `var camview: UIView!`
    `var previewView: UIView!`
    
    `func setupCam() {
        let cambounds = camcontainer.bounds
        self.camview = UIView(frame: cambounds)
        if let camView = self.camview {
            camView.autoresizingMask = [.flexibleHeight, .flexibleWidth]
            camView.backgroundColor = blueColor
            NextLevel.shared.previewLayer.frame = camView.bounds
            camView.layer.addSublayer(NextLevel.shared.previewLayer)
            self.camcontainer.insertSubview(camView, at: 0)
        }
    }`

and the result that I am getting is below. THe blue area is where I want the camera to be fully contained to the margins and not have the blue background visible: 

![img_e6ac119f4da5-1](https://user-images.githubusercontent.com/24389003/50610496-01336f80-0e88-11e9-8620-cc0cd5183d64.jpeg)

What is wrong here?

**Comment by clonezer** [comment]
you should call `setupCam()` function in `didLayoutSubviews()`
