### ISSUE TITLE
Retrieve thumbnail image of captured video

### ISSUE THREAD

**Issue by pribeh** [NextLevel/NextLevel#164]
Using the NextLevel library we are trying to get the file path of an image that is taken after CapturePhotoFromVideo() is called. The filepath is needed to be able to upload the photo taken to an online server.

We are able to retrieve the filepath for a video that is saved to the photo library, but struggling to find the path for an image.

The call is made on line 395 in CameraViewController.swift

Calls the function on line 2220 CapturePhotoFromVideo

Is this possible with NextLevel? Maybe we're just missing something but we're unable to find anything in the NextLevel documentation that explains how to do this. We thought about just getting the last image taken from the PhotoLibrary, but that won't work according to an answer from a post on stackoverflow. 

We'd appreciate any help as we're really stuck on this one.

**Comment by piemonte** [comment]
hey @pribeh the image data is just handed off in an array:

https://github.com/NextLevel/NextLevel/blob/master/Sources/NextLevel.swift#L2290-L2291

this gives you the freedom to write it to disk or store it as an asset in the photo library based on whatever you'd like to do.

**Comment by pribeh** [comment]
@piemonte thanks!

**Comment by donileo** [comment]
Is there a way to capture a photo from the first frame or any specified time interval or frame number?

**Comment by piemonte** [comment]
hey @donileo i'm sure you can update it to do so, but it currently doesn't
