### ISSUE TITLE
Filters on videos pls

### ISSUE THREAD

**Issue by PilotPetrov** [NextLevel/NextLevel#165]
Please when will be available so we can apply filters with cifilter

**Comment by alittle433** [comment]
@PilotPetrov I use next level as a management system of all my clips, then create a custom AVMutableVideoComposition. And by using AVVideoCompositing protocol, you are able to get each frame and manipulate it either with CIFilters or Metal and apply transitions etc. 

I would highly recommend this approach as it gives you more flexibility and control over your videos. I'm considering writing a blog post about my experience as there is little to no documentation/tutorials on how to use the powerful framework that is AVFoundation.

**Comment by PilotPetrov** [comment]
yes can you shared, you will be more than helpful :), thanks buddy :)

**Comment by alittle433** [comment]
@PilotPetrov This was my first ever blog post, so forgive me if there is any uncertainty or I am unclear at points. [https://medium.com/@alex_19513/real-time-video-editing-swift-2cc18f198c83](url)

**Comment by piemonte** [comment]
it's a nice idea for a future release

📎 https://github.com/NextLevel/NextLevel/issues/39
