### ISSUE TITLE
photocapture with volume button

### ISSUE THREAD

**Issue by pribeh** [NextLevel/NextLevel#174]
I'm not sure if [photocapture with the volume button ](https://github.com/NextLevel/NextLevel/issues/4)was ever implemented. If so, could you please point out where in the docs I can find it. Maybe I'm just blind – thanks.

**Comment by piemonte** [comment]
hey @pribeh i never merged this in because some apps had been rejected for overriding the hardware button functionality.

**Comment by pribeh** [comment]
Sorry, had no idea!
