### ISSUE TITLE
Video wrong size

### ISSUE THREAD

**Issue by AndreiEvstratenko** [NextLevel/NextLevel#178]
Hey, Patrick!
Awesome product!

Some minor bugs:

When I use `NextLevel.shared.videoConfiguration.dimensions = CGSize(width: 1080, height: 1920)` I get a video with wrong resolution (1072  x  1920)

When I use `NextLevel.shared.videoConfiguration.aspectRatio = .widescreenLandscape` - doesn't change anything.

Do you have any thoughts? Maybe I use it wrong?

**Comment by piemonte** [comment]
hey @AndreiEvstratenko i just haven't implemented this yet:

https://github.com/NextLevel/NextLevel/blob/master/Sources/NextLevelConfiguration.swift#L239

we could add a `custom` type that lets you specify specific dimensions instead of computing a ratio.

**Comment by piemonte** [comment]
@AndreiEvstratenko oops, i did add a custom type at some point, I recommend using that aspect ratio instead of widescreen.
