### ISSUE TITLE
iphone 6 & 6s black preview 

### ISSUE THREAD

**Issue by thegodland** [NextLevel/NextLevel#181]
Hi. When i am using with video, the preview for iphone 6 and 6s is black and no image at all whereas above 6s is ok. Do you have any idea why it happens? Thank you

**Comment by piemonte** [comment]
hey @thegodland i don't have one of those devices to test on but it should be properly supported by the GPU

https://developer.apple.com/library/archive/documentation/DeviceInformation/Reference/iOSDeviceCompatibility/HardwareGPUInformation/HardwareGPUInformation.html

**Comment by piemonte** [comment]
does this occur with the sample application?

**Comment by thegodland** [comment]
Hi Thank you for quick reply. I find why cuz I didn't notice audio authorization should be requested as well for video recording. Thank you
