### ISSUE TITLE
When open and close camera back and forth quickly, the camera display old view

### ISSUE THREAD

**Issue by thegodland** [NextLevel/NextLevel#182]
I am trying to use camera to record video but if i open and close and reopen camera, quickly and repeat this action. somehow, when camera is displayed, it will show last time view maybe 1 second then show current one sometimes. And sometimes this behavior will also ended black screen or can't record. Any reason why? Much appreciated. The implementation is similar to example project as far as i see.

**Comment by P7S1** [comment]
I have the same issue

**Comment by bishalg** [comment]
@thegodland @P7S1 : can you share some code ? it will be easier to debug !
