### ISSUE TITLE
How to set desired pixel format? is this supported?

### ISSUE THREAD

**Issue by troy-lamerton** [NextLevel/NextLevel#186]
I am using NextLevel's video output in Unity 3D.

To make it work nicely, I need to set the pixel format of video output to 32BGRA.

NextLevel internally creates the video output and chooses the pixel format.
Relevant code in NextLevel.swift `addVideoOutput()`.

So what would be the correct way to expose a way to set `kCVPixelBufferPixelFormatTypeKey`?

I am happy to make a pull request with the desired change.

**Comment by piemonte** [comment]
hey @troy-lamerton using the videoConfiguration, you can specify it in the options dictionary:

https://github.com/NextLevel/NextLevel/blob/master/Sources/NextLevelConfiguration.swift#L144-L145

you're welcome to add a property but it'd need some type of check to see if that buffer format is available on the particular device.

https://github.com/NextLevel/NextLevel/blob/master/Sources/NextLevelConfiguration.swift#L451-L455

hope that helps! thanks for the project interest. ✌️
