### ISSUE TITLE
How to get quality improve for Image & Video capture with NextLevel - compare to defult iphone 11, 11 pro & 11 max device.

### ISSUE THREAD

**Issue by akashthakkar09** [NextLevel/NextLevel#189]
The image and video quality are not as same as the default iPhone's camera quality. 

How to get quality improvement by using NextLevel as same as the default one?

iPhone Xs, 11 serious camera quality is much higher compared to NextLevel custom camera capture output. can we have any solution to improve the quality of image /videos?

**Comment by piemonte** [comment]
hi @akashthakkar09 thanks for the interest in NL. you can change all of the image and compression settings via the configuration objects. my advise is to remove compression and try match your goals before optimizing.  

NextLevelVideoConfiguration
NextLevelPhotoConfiguration
