### ISSUE TITLE
iPhone 11 : selfie (front-camera) issue.

### ISSUE THREAD

**Issue by akashthakkar09** [NextLevel/NextLevel#190]
I'm facing the issue "flipCaptureDevicePosition" to rotate the camera with font especially on iPhone 11.

I'm using below code to change the mode of the camera :

`NextLevel.shared.flipCaptureDevicePosition()`

By apply this its working fine with iPhone X, 8, 7 & all other devices but the same code is making an issue with iPhone 11 to show font camera view.

I have also make sure Im using the very updated pod version 0.16.0 but still having an issue to get the required output.

Kindly help me in this case.

**Comment by bishalg** [comment]
@akashthakkar09  : any update on this issue?
I am checking the code on iPhone 11 and its working for above code. 

As of today on May - 20, POD says  version 0.16.3
