### ISSUE TITLE
Crash on iPhone 6s when capturing photo ("processedFileType must be present in availablePhotoFileTypes")

### ISSUE THREAD

**Issue by Moriquendi** [NextLevel/NextLevel#196]
**NextLevel release version: 0.16**

Users of my app are reporting crashes when capturing photos.
I analyzed crash reports and it looks the crashes occurs **only on `iPhone 6s` (iOS 13.3.0)**.

Crash occurs after calling `NextLevel.shared.capturePhoto()` and the message is:

> *** -[AVCapturePhotoOutput capturePhotoWithSettings:delegate:] settings.processedFileType must be present in self.availablePhotoFileTypes

My camera configuration code is pretty straightforward:
```swift
// Configure camera
let nextLevel = NextLevel.shared
nextLevel.captureMode = .photo
nextLevel.photoDelegate = self
nextLevel.photoConfiguration.preset = .high
```

I don't have iPhone 6s so it's hard for me to debug it but perhaps you folks will know where the issue is coming from.

___

Edit: my guess is that NextLevel sets codec to `hevc` on all iOS 11 devices but it's only supported on iPhone 7 and newer. iPhone 6s can process hevc photos but they can't capture in that format.

**Comment by willi** [comment]
Just check for HEVC support and set the correct codec for iPhone 6 models.
`let supportsHEVC = AVAssetExportSession.allExportPresets().contains(AVAssetExportPresetHEVCHighestQuality)
NextLevel.shared.photoConfiguration.codec = supportsHEVC ? .hevc : .jpeg`

**Comment by ivanzoid** [comment]
Probably this code should be in `NextLevelPhotoConfiguration.init`
