### ISSUE TITLE
Green lines on right and bottom border of video footage captured

### ISSUE THREAD

**Issue by thexande** [NextLevel/NextLevel#20]
I might be missing something, but is anyone else getting a few pixels of green on the bottom and the right border on video captured using next level?

Here is an example:

https://firebasestorage.googleapis.com/v0/b/sparkpoll-f7275.appspot.com/o/videos%2Foption_one?alt=media&token=1e186ec7-8d65-4b7a-8d3e-af78618c1650

**Comment by piemonte** [comment]
hey @thexande i wasn't able to reproduce this. if you can using the sample project, please let me know. along with the device type and video configuration.

**Comment by thexande** [comment]
@piemonte I will extend the sample project on my fork to include both this issue and #19

**Comment by piemonte** [comment]
@thexande sure thing, let me know what it's there. i think i might have encountered the same issue you're seeing when i was building this up and it was fixed with a simple configuration change but i don't remember exactly

**Comment by priyeshmarvi** [comment]
Your video rendersize width should be even or divisible by 4.

check this [discussion link]( https://discussions.apple.com/message/8525272#8525272) 

>Be aware. If you choose a resolution which is not divisible by 16, 8 or 4, you might end up with a 1px green border at either bottom or right side of your frame. I have seen this problem with

>"If the horizontal or vertical size is not divisible by 16, then the encoder pads the image with a suitable number of black "overhang" samples at the right edge or bottom edge. These samples are discarded upon decoding. For example when coding HDTV at 1920x1080, an encoder appends 8 rows of black pixels to ht eimage array, to make the row count 1088."

**Comment by BhavinBhadani** [comment]
to solve this issue make sure your video rendersize width should be even or divisible by 4.

check this [discussion link]( https://discussions.apple.com/message/8525272#8525272) 

>Be aware. If you choose a resolution which is not divisible by 16, 8 or 4, you might end up with a 1px green border at either bottom or right side of your frame.

>"If the horizontal or vertical size is not divisible by 16, then the encoder pads the image with a suitable number of black "overhang" samples at the right edge or bottom edge. These samples are discarded upon decoding. For example when coding HDTV at 1920x1080, an encoder appends 8 rows of black pixels to ht eimage array, to make the row count 1088."

**Comment by piemonte** [comment]
thanks @BhavinBhadani ✌️
