### ISSUE TITLE
Build Succeeded but Project NextLevel app doesn't run in XCode 11 [Screenshots uploaded !!!]

### ISSUE THREAD

**Issue by TilakMaddy** [NextLevel/NextLevel#201]
There is a sample implementation app for this framework  - /Project/NextLevel
I have cloned the WHOLE master repo. When I hit the run button it says build succeeded but doesn't run in the simulator

<img width="1392" alt="Screenshot 2020-01-21 at 9 41 10 AM" src="https://user-images.githubusercontent.com/11134428/72774867-3b59e580-3c32-11ea-9812-612dcb1ee658.png">

Also notice that NL.app is red colored in the left view pane indicating some sort of error although the build was successful . If I select NL.app this is what is shown in the right pane

<img width="334" alt="Screenshot 2020-01-21 at 9 43 05 AM" src="https://user-images.githubusercontent.com/11134428/72774980-a73c4e00-3c32-11ea-871e-f04998a931ff.png">

**Comment by piemonte** [comment]
hi @TilakMaddy thanks for the project interest. since this is a hardware/camera focused project simulator support is limited.

**Comment by TilakMaddy** [comment]
yeah cool
