### ISSUE TITLE
FaceTime AudioChannelLayout Crash

### ISSUE THREAD

**Issue by iPhonig** [NextLevel/NextLevel#209]
Steps to recreate - FaceTime someone, and go into a view where NextLevel is initialized and the camera preview is being displayed. 

\"NSInvalidArgumentException" - reason: "*** -[AVAssetWriterInput initWithMediaType:outputSettings:sourceFormatHint:] AudioChannelLayout channel count does not match AVNumberOfChannelsKey channel count"

Any ideas on this or has anyone else run into it?

**Comment by piemonte** [comment]
thanks for filing, this is a duplicate for

📎 https://github.com/NextLevel/NextLevel/issues/205
