### ISSUE TITLE
Orientation issues for any media (video or photo) once switching camera.

### ISSUE THREAD

**Issue by 501336North** [NextLevel/NextLevel#21]
Orientation is fine as long as the input camera isn't modified.  Once camera is changed (even if set back to original camera before taking video or photo) the orientation is screwed.

**Comment by piemonte** [comment]
thanks @501336North will look into it

**Comment by piemonte** [comment]
hey @501336North let me know if master works better, thanks

**Comment by f2m2rd** [comment]
Hi @piemonte - I believe this bug still exists.   If you set the `deviceOrientation` to `.portrait` and you switch the `devicePosition` from `.front` to `.back` camera, the output of the video is in landscape.
