### ISSUE TITLE
How to disable mic voice while video recording with sound? 

### ISSUE THREAD

**Issue by AdnanAliShabir** [NextLevel/NextLevel#215]
I would like to congratulate you on building such an incredible engine.
I want to record video with sound like TikTok but the problem is my microphone voice is also recorded so how i can fix it to only play the selected sound? Thank you!

**Comment by bishalg** [comment]
Hi @AdnanAliShabir,

` NextLevel.shared.captureMode = .videoWithoutAudio`

Should record the video without Audio.

**Comment by AdnanAliShabir** [comment]
@bishalg Thank you, I also did in the same way.
