### ISSUE TITLE
Local video optimization

### ISSUE THREAD

**Issue by rcfrias** [NextLevel/NextLevel#222]
Hi, I am recording small 3 minute clips (max) with NextLevel and then uploading them to a server.  I've noticed it could take a while until the device finishes uploading the recorded video.

I am looking for alternatives to optimise the video before uploading, some sort of optimization process "Whatsapp"-like before sharing.

I've used ffmpeg and found a way to use it on-device, but I am unsure if this will help anyhow or it would just add overhead to the already build in compression in NextLevel library. Thank you for your comments.

**Comment by piemonte** [comment]
hey @rcfrias you can process the video using [NextLevelSessionExporter](https://github.com/NextLevel/NextLevelSessionExporter), which could allow you to make multiple versions or use various encodings and compression-settings depending on your needs.
