### ISSUE TITLE
[Question] .videoWithoutAudio without audio recording permission?

### ISSUE THREAD

**Issue by Tueno** [NextLevel/NextLevel#225]
Hi, thanks for the awesome library.
I have a question about audio recording permission on iPhone.

I'd like to create the app has a feature of recording video without audio.
Since the app doesn't record audio, I think it's more natural if the app doesn't request audio recording permission.

So can I avoid audio recording permission requesting with using NextLevel?
(As I'm not familiar with AVFoundation, I'm not 100% sure it's possible even I create that with scratch.)

**Comment by Tueno** [comment]
I have noticed that I need to set captureMode before starting session to avoid requesting audio recording permission.
Let me close this issue. Thanks.

**Comment by piemonte** [comment]
@Tueno thank you for the project interest and the comments. i'll update the documentation to reflect this.
