### ISSUE TITLE
Xcode 12 compiler error

### ISSUE THREAD

**Issue by cincas** [NextLevel/NextLevel#229]
Has anyone encounter this issue when running in Xcode 12?

Looks like an iOS 14 SDK issue, but not 100% sure. 
![image](https://user-images.githubusercontent.com/1229438/93409015-435d4880-f8d9-11ea-93ad-3af955ed872c.png)

I could find `availableVideoCVPixelFormatTypes` in Objc header file, but somehow it is not visible in Swift.
![image](https://user-images.githubusercontent.com/1229438/93409129-8a4b3e00-f8d9-11ea-9573-0a3e954c3931.png)

And here is Apple's documentation for `availableVideoPixelFormatTypes` which is `nonobjc` but still, cannot find it in Swift header

https://developer.apple.com/documentation/avfoundation/avcapturevideodataoutput/2926555-availablevideopixelformattypes

NextLevel version: 0.16.3

**Updates**
Checked in XCode 11.7, here is the definition for that property 
![image](https://user-images.githubusercontent.com/1229438/93413415-938cd880-f8e2-11ea-8d81-d6d788bcf137.png)

**Comment by piemonte** [comment]
@cincas thanks for the issue, will investigate

**Comment by piemonte** [comment]
reminds me of this issue back in iOS 11 GM

📎 https://github.com/NextLevel/NextLevel/commit/ca50c19c4ee940092fd060abe5acce2144b69226
📎 https://developer.apple.com/forums/thread/86810

**Comment by piemonte** [comment]
added a temporary workaround until there's some clarity on why that symbol is missing

**Comment by pixelmatrix** [comment]
I've noticed this for the past couple of days on beta 6 and the GM. Very unfortunate, but it seems Apple didn't properly export the headers for some properties with the Xcode 12 GM.

The good news is that it only affects building for the simulator. Building for a real device is unaffected, so you could add a compiler directive like `#if targetEnvironment(simulator)` as a better workaround.

**Comment by pixelmatrix** [comment]
The issue remains in Xcode 12.2 Beta 1

**Comment by piemonte** [comment]
@pixelmatrix thanks for the help! not on my game, should have built for the device too. 😄

**Comment by pixelmatrix** [comment]
Totally understandable. They're supposed to be the same! It took me a while to discover that as well.
