### ISSUE TITLE
Sample project fail?

### ISSUE THREAD

**Issue by davidseek** [NextLevel/NextLevel#23]
I have just downloaded and tried the sample project and it's like dead?!
You start the App, you got 3 Buttons, nothing really happens. You press the checkmark and it says saved. I don't get any feedback like recording time or a final video?
There are like 1 Billion lines of code, but nothing really happens. Is this a wanted thing?

**Comment by piemonte** [comment]
Hey @davidseek thanks for the interest. The sample project is just a barebones implementation.

If you'd like to build in feedback for the sample project, feel free. Other than that, the features supported are listed on the read me. Documentation is almost complete.

**Comment by piemonte** [comment]
I'll post a link to the documentation here when it's fully posted, expected in the next update.

**Comment by davidseek** [comment]
Alright. I just came up with your Framework by accident and wanted to know what it does, so I was downloading the sample project and it did kinda nothing.
You know, not the worst idea to have a final project as the sample project... For people wanting to check it out. But it's your thing, Bro.

**Comment by piemonte** [comment]
@davidseek i completely agree, when i get some time i'll add in more functionality for it:

📎 https://github.com/NextLevel/NextLevel/issues/4

**Comment by davidseek** [comment]
I'll keep following it.

**Comment by piemonte** [comment]
📚 https://nextlevel.github.io/NextLevel/
