### ISSUE TITLE
Swift 2.3 Support?

### ISSUE THREAD

**Issue by Kareemarab** [NextLevel/NextLevel#24]
Is there anyway I can use this in my Swift 2.3 project?

**Comment by piemonte** [comment]
Hey @Kareemarab – unfortunately there isn't a means to mix multiple versions of swift as of right now.

I don't see Xcode continuing to support the legacy 2.3 compiler over the long haul, so I recommend upgrading as soon as you can.

**Comment by davidseek** [comment]
Support of Swift 2x will be dropped with Xcode 8.2
You can see it in the current Beta release information.
Therefore with the next release Update of Xcode 8, Swift 2x will be dropped.
