### ISSUE TITLE
NSPhotoLibraryAddUsageDescription crashes the app on save

### ISSUE THREAD

**Issue by antonkarev** [NextLevel/NextLevel#244]
Hi, Patrick! Thank you for your great work! Saving a photo or video on iOS 14.4 crashes your sample Project app if used with `NSPhotoLibraryAddUsageDescription` (the write-only nicer OS permission dialog):

`This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data.`

`NSPhotoLibraryUsageDescription` that grants both read and write permission works great (but the OS permission dialog is scary - Allow Access to All Photos).

**Comment by piemonte** [comment]
hey @antonkarev thanks for the note. i've been meaning to overhaul the sample project for some time but haven't had the chance. can add this key in for you. ✌️
