### ISSUE TITLE
App rejected in app store

### ISSUE THREAD

**Issue by soonawan786** [NextLevel/NextLevel#249]
I am use your NextLevel to render and record videos in app but when trying to submit app to app store its reject due to minimum features of ARKit is use can you please help me to resolve this issue

**Comment by piemonte** [comment]
hi @soonawan786, i'm sorry to hear you're hitting this. i don't have enough detail about your app to help but my key recommendation is, if you're not using ARKit do not include the ARKit flag in your Podfile. the README explains this in detail:

📎 https://github.com/NextLevel/NextLevel/blob/main/README.md#important-configuration-note-for-arkit-and-true-depth

**Comment by qhu91it** [comment]
So how about using swift packager manager? do I need to do something?

**Comment by piemonte** [comment]
📎 https://github.com/apple/swift-evolution/blob/main/proposals/0238-package-manager-build-settings.md

you can pass build settings with spm too
