### ISSUE TITLE
Is there a demo?

### ISSUE THREAD

**Issue by HackShitUp** [NextLevel/NextLevel#25]

**Comment by piemonte** [comment]
hey @HackShitUp, thanks for the interest. ✌️

you can build and run the target in the sample project after launching the workspace:
https://github.com/NextLevel/NextLevel/tree/master/

and learn by more just from the docs:
http://nextlevel.github.io/NextLevel/

**Comment by CameraPost** [comment]
Is there a demo that includes all of the features set to be on? When I run the demo project, and press to record, it didn't appear to record. And I imagine there are a number of features that aren't shown in the demo. Thanks!

**Comment by piemonte** [comment]
@CameraPost there is not but you can add examples here

https://github.com/NextLevel/examples
