### ISSUE TITLE
Project's website metadata is outdated: http://nextlevel.engineering webpage is dead

### ISSUE THREAD

**Issue by rogerluan** [NextLevel/NextLevel#252]
Hello 👋 

I know this seems silly, but http://nextlevel.engineering being dead brings less trust to this library. Make it seems like the company that used to support this repo is no longer maintaining it. I'd either remove the link or update it 😊

**Comment by piemonte** [comment]
hey @rogerluan – thanks for the note. there's no company, it's just me. i've renewed the domain, will be working again shortly.

**Comment by rogerluan** [comment]
Thanks for clarifying and for the prompt response @piemonte ! 🤗
