### ISSUE TITLE
Play Music while Recording

### ISSUE THREAD

**Issue by sulamatraore** [NextLevel/NextLevel#26]
Hello!

First off, I would like to congratulate you on building such an incredible engine. It has really accelerated development on my project. However, I was just wondering if there is any way to implement the ability to play music during a session, similar to that of Snapchat, Vine, and Instagram Stories. I've tried setting the AVAudioSession to both Ambient and PlayToRecord, but the music would still pause on the opening of the camera session. 

Thank you in advance!

**Comment by piemonte** [comment]
hey @sulamatraore thanks much. i haven't experimented much with audio recording from a specific source but you can hack the audio session such that NextLevel will record what the speakers are playing without the app pausing an existing session. won't be able to give you more info outside of that.

https://github.com/NextLevel/NextLevel/blob/master/Sources/NextLevel.swift#L570

**Comment by sulamatraore** [comment]
Hi again.

When I manage to get music playing while the camera is open, the session just stops. Is there a reason for this? Thanks in advance
