### ISSUE TITLE
Adjust exposure crash

### ISSUE THREAD

**Issue by lczalh** [NextLevel/NextLevel#260]
Call this method to crash
NextLevel.shared.expose(withDuration: 0.1, durationPower: 4, minDurationRangeLimit: 1.0 / 2000.0)

dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib:/Developer/Library/PrivateFrameworks/GPUTools.framework/libglInterpose.dylib
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureDevice setExposureModeCustomWithDuration:ISO:completionHandler:] Unsupported - use -[isExposureModeSupported:AVCaptureExposureModeCustom]'

**Comment by rojo69** [comment]
This was fixed by PR #266.
