### ISSUE TITLE
Background Audio Stops When Session Starts

### ISSUE THREAD

**Issue by strohat** [NextLevel/NextLevel#262]
The goal is to record the audio background if it is playing. However, as soon as the camera starts all background music is automatically turned off.

Question is -- 
1) How can we keep the background music playing?
2) How can we record it instead of/ With other audio?

Amazing work by the way, really amazing.

**Comment by piemonte** [comment]
hey @strohat thanks for the project interest. this is in how you configure your app's `AVAudioSession`. you'll want to tell NextLevel to not make any audioSession changes by setting the `automaticallyConfiguresApplicationAudioSession` property to false:

https://github.com/NextLevel/NextLevel/blob/2e890c96676718c3ac08673af92d298ce5055a83/Sources/NextLevel.swift#L283-L284

then NextLevel will use your app's designated audio routing and AVFoundation will behave as expected:

https://developer.apple.com/documentation/avfoundation/avcapturesession/1620477-automaticallyconfiguresapplicati
