### ISSUE TITLE
flash functions

### ISSUE THREAD

**Issue by monish152** [NextLevel/NextLevel#27]
Hi There,

Thanks for wonderful library. In pbjvision we had flash on/off and maximum length video function. Is there any function in nextlevel about same?

Thanks
Monish

**Comment by monish152** [comment]
PBJVision.sharedinstance.capturevideoseconds in pbjvision we had this function

**Comment by piemonte** [comment]
hey @monish152, thanks much.

the max length is part of videoConfiguration:

https://github.com/NextLevel/NextLevel/blob/master/Sources/NextLevelConfiguration.swift#L92

💡 flash on/off:

https://github.com/NextLevel/NextLevel/blob/master/Sources/NextLevel.swift#L1237-L1270

📚 there's some docs if you need more info:

http://nextlevel.github.io/NextLevel/

**Comment by monish152** [comment]
Thanks for flash point. Sorry for typing mistake. I have asked for PBJVision.sharedinstance.capturevideoseconds

**Comment by piemonte** [comment]
@monish152 np. Nextlevel's session property provides it:

https://github.com/NextLevel/NextLevel/blob/master/Sources/NextLevelSession.swift#L91-L95

**Comment by monish152** [comment]
Thanks @piemonte this session provides the sum of all recorded clips. Do we have any functions that provide session timing while recording?
