### ISSUE TITLE
Flash not working.

### ISSUE THREAD

**Issue by replytoashish008** [NextLevel/NextLevel#28]
Hi, 

I have include this library in one of my project . I tried to on the Flash using following code.

NextLevel.sharedInstance.flashMode = .on

But it is not working. it always return "NextLevel.sharedInstance.flashMode" off.

Please check the issue.

**Comment by piemonte** [comment]
hey @replytoashish008 thanks for the interest. a session needs to be started before setting any of the modes, this ensures there is an active capture device.

what happens when your code approaches this line?
https://github.com/NextLevel/NextLevel/blob/master/Sources/NextLevel.swift#L1258
