### ISSUE TITLE
crash on launch

### ISSUE THREAD

**Issue by monish152** [NextLevel/NextLevel#29]
Hi Piemonte,

Once my app is crashing due to other reasons. and after that when I opening my app its giving below crash. And its not opening app 2-3 times.

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureSession addInput:] Multiple audio/video AVCaptureInputs are not currently supported'
*** First throw call stack:
(0x186de51b8 0x18581c55c 0x18e5c8c70 0x1011efe2c 0x1011edf00 0x1011ed6bc 0x1011ee530 0x1011ec188 0x1011e79d8 0x101fbd258 0x101fbd218 0x101fcaaec 0x101fc0ce0 0x101fcb088 0x101fcce2c 0x101fccb78 0x185e772a0 0x185e76d8c)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by piemonte** [comment]
hey @monish152 make sure you've got the appropriate permissions keys in your info.plist. other than that, i can't verify your issue is happening within this library.

**Comment by piemonte** [comment]
hey @monish152 can you share more information? maybe your nextlevel setup lines and a way to reproduce this with the sample project?

**Comment by monish152** [comment]
ok I will send line number where its crashing again and again.

**Comment by piemonte** [comment]
@monish152 the line number is provided there in your stack trace there based on addInput, i'm just curious on what the calls are that's producing this state. if you can show me using the sample project, i can help. otherwise, probably not.
