### ISSUE TITLE
Issue related to Video formate when recorded 

### ISSUE THREAD

**Issue by replytoashish008** [NextLevel/NextLevel#30]
Hi,

I have been updating my code from PBJVision to NextLevel in one my project. I am getting an issue related to video type when recorded and upload on server with mineType: "video/mp4"
 
It is giving a success message through PBJVision but giving an error with status code  422.

As per initial thought it seem that the video recording/saving formate is different.

Thank you.

**Comment by piemonte** [comment]
hey @replytoashish008 there isn't enough information here for me to understand the problem. if you can determine the configuration you're expecting and what the actual result is, that would be helpful.

**Comment by monish152** [comment]
I am facing same issue. I think there is some changes in video format in nextlevel. In pbvision video uploading was working fine but in nextlevel its giving error response.

**Comment by piemonte** [comment]
@monish152 thanks, can you share the specific details for the configuration? sample outputs?

**Comment by monish152** [comment]
HI @piemonte  our backend is supporting only square video. In pbjvision we had square configuration but in nextlevel I think its missing. Can you please confirm by when we can expect this enhancement?

**Comment by piemonte** [comment]
hey @monish152 you can specify a rectangle in the video output configuration without relying on a preset. you're welcome to contribute these changes if you need them in the library.

**Comment by replytoashish008** [comment]
The backend has the condition that required the video in square shape to save video. Issue is resolved by using the "dimensions" property in videoconfiguration.
