### ISSUE TITLE
regarding presence of outputFormat of video and photo

### ISSUE THREAD

**Issue by replytoashish008** [NextLevel/NextLevel#31]
Hi,

I have been updating my code from PBJVision to NextLevel in one my project. I am getting an issue related in finding the PBJOutputFormat type enum . I am trying to get the image/video in square formate .

Please let me know if there is any enum to use square output formate.

Thank you.

**Comment by piemonte** [comment]
@replytoashish008 you can specify the dimensions of the video using the configuration. presets for videoConfiguration is something to be added in the future:

📎 https://github.com/NextLevel/NextLevel/issues/5
