### ISSUE TITLE
support for real-time recorded progress

### ISSUE THREAD

**Issue by replytoashish008** [NextLevel/NextLevel#32]
Hi,

I have been updating my code from PBJVision to NextLevel in one my project. I am getting an issue in live update of duration of recorded value . I am using the value :- 

`session.duration.seconds'

but it return the constant value of last video duration clip . mean to say it is not live updating. I am using the value in following video delegate method:- 

```
func nextLevel(_ nextLevel: NextLevel, didAppendVideoSampleBuffer sampleBuffer: CMSampleBuffer, inSession session: NextLevelSession) {
    ` log.debug("\(session.duration.seconds)..")`
)
```

Please check the issue.

Thank you.

**Comment by piemonte** [comment]
hey @replytoashish008 thanks for all the feedback. real-time recorded seconds is a nice idea. i didn't really think about that when putting this library together. i think i need to surface the current clip within a session, or just have the duration update in realtime. not something i can do personally anytime soon but will in the future.

**Comment by cemaleker** [comment]
Currently if you are facing this issue you can use `let current = session.duration.seconds + session.currentClipDuration.seconds` for total session duration.

Meanwhile I think `session.duration` should include `session.currentClipDuration`.
