### ISSUE TITLE
Type 'UIViewController' does not conform to protocol 'NextLevelDelegate'

### ISSUE THREAD

**Issue by HackShitUp** [NextLevel/NextLevel#33]
I used CocoaPods and imported the module in my class file. Am I doing something wrong?

**Comment by piemonte** [comment]
hey @HackShitUp sounds good so far. just ensure your ViewController implements the protocol.

```swift
class myViewController: UIViewController, NextLevelDelegate {
//...

// NextLevelDelegate implementations here
```

If you follow the implementation in the sample proj, it should help:

https://github.com/NextLevel/NextLevel/blob/master/Project/NextLevel/CameraViewController.swift
