### ISSUE TITLE
Development  Targer Problem

### ISSUE THREAD

**Issue by ancheng1114** [NextLevel/NextLevel#36]
thanks for your good library.
I tried to add NextLevel in pod.
It need deployment_target 10.0.
Can you make it to work on 9.0 also ?

**Comment by piemonte** [comment]
hey @ancheng1114 thanks much! ✌️

unfortunately, i haven't done any testing on iOS versions lower than 10. there aren't plans to support those versions, so my recommendation is to manually install just by copying the source files and seeing what works.
