### ISSUE TITLE
Image pixelete when using capture photo from video

### ISSUE THREAD

**Issue by replytoashish008** [NextLevel/NextLevel#38]
Image pixelate when using capture photo from video.I required a image of high quality photo. I am using the the following code :- 

`NextLevel.sharedInstance.capturePhotoFromVideo()`

Properties that I am setting to shared instance of NextLevel:- 

```
let nextLevel = NextLevel.sharedInstance
        nextLevel.deviceOrientation = .portrait
        nextLevel.videoConfiguration.maximumCaptureDuration = CMTimeMakeWithSeconds(maximumDuration, 600)
        
        //   video configuration
        nextLevel.videoConfiguration.bitRate = 2000000
        nextLevel.videoConfiguration.scalingMode = AVVideoScalingModeResizeAspectFill
        
        // audio configuration
        nextLevel.audioConfiguration.bitRate = 128000
        
        nextLevel.isVideoCustomContextRenderingEnabled = true
        nextLevel.videoConfiguration.preset = AVCaptureSessionPresetHigh
```

**Comment by piemonte** [comment]
hi @replytoashish008 

the quality of a photo from video is limited by the fact that you're encoding a video frame without changing modes, so there isn't much to do besides increasing the quality of the video itself.

**Comment by monish152** [comment]
and how we can increase quality of video?

**Comment by monish152** [comment]
Video quality comparision: 

This we have recorded from our app:
https://dl.dropboxusercontent.com/u/53512841/709D907C-E9F3-4F1F-96C2-BDABAACCCB01-NL-clip.0.mp4

This we have recorded from iphone default camera
https://dl.dropboxusercontent.com/u/53512841/IMG_3046.MOV

It seems pixelation in our app. @piemonte can you please have a look.

**Comment by monish152** [comment]
And in image left side video recorded from nextlevel and right side video recorded from default apple. left seems pixelated
![screen shot 2017-01-13 at 2 16 07 pm](https://cloud.githubusercontent.com/assets/1301491/21924266/7e2601e0-d99e-11e6-8f10-b982e0bba1c0.png)

**Comment by piemonte** [comment]
Configuration of NextLevel can be done using the `NextLevelVideoConfiguration` object. If you're trying to match the default iOS camera application, then you need to look at what you're using for compression settings as well as your preset, both in `NextLevelVideoConfiguration`.

📚 https://nextlevel.github.io/NextLevel/
