### ISSUE TITLE
🛠 sample proj additions

### ISSUE THREAD

**Issue by piemonte** [NextLevel/NextLevel#4]
- [x] example clip saving
- [x] add a focus indicator example
- [x] add pan to zoom video example
- [ ] add capture support when using the hardware volume buttons

**Comment by Wouter125** [comment]
Could you also set up some sample of saving a recorded clip? Much appreciated!

**Comment by piemonte** [comment]
@Wouter125 sure thing

**Comment by delta98** [comment]
I'd like it if you could add applying a real-time filter?

**Comment by piemonte** [comment]
📎 https://github.com/NextLevel/NextLevel/issues/71

**Comment by piemonte** [comment]
📎 https://github.com/nextlevel/examples
