### ISSUE TITLE
Dynamic Video Overlays

### ISSUE THREAD

**Issue by blazierkyle** [NextLevel/NextLevel#45]
Hi,

I'm using your video capture library in an app I'm making, thanks for all the work!

I am trying to add dynamic overlays to video I'm capturing using this library, but I've been unsuccessful thus far. I'm trying to capture the overlay in a video that'll be saved so I tried adding it to the preview layer but can't seem to get it to show up.

Thanks!

        let subtitleText = CATextLayer()
        subtitleText.fontSize = 72
        subtitleText.frame = CGRect(x: 0.0, y: 50.0, width: UIScreen.main.bounds.width, height: 100.0)
        subtitleText.string = "Text Overlay!"
        subtitleText.alignmentMode = kCAAlignmentCenter
        subtitleText.foregroundColor = UIColor.green.cgColor
        subtitleText.shadowOpacity = 1.0
        subtitleText.shadowOffset = CGSize(width: 0.0, height: 0.0)
        subtitleText.shadowRadius = 6.0
        
        let textOverlayLayer = CALayer()
        textOverlayLayer.addSublayer(subtitleText)
        textOverlayLayer.frame = CGRect(x: 0.0, y: 0.0, width: UIScreen.main.bounds.width, height: UIScreen.main.bounds.height)

       // Neither of these work
        NextLevel.sharedInstance.previewLayer.addSublayer(textOverlayLayer)
        NextLevel.sharedInstance.previewLayer.insertSublayer(textOverlayLayer, at: 0)

**Comment by piemonte** [comment]
Hey @blazierkyle thanks for the interest. I've included some instructions on reading sample buffers for modification/analysis but also providing them back for recording.

Personally, I don't use preview layers for doing this type of task. I usually will modify the buffers themselves. That would probably require doing snapshots of the view, and then saving/sending the UIImage as a pixelBuffer to NextLevel, which would dramatically effect performance on the CPU.

I've had other folks request a "NextLevelView" type project for just that, but I won't be able to provide that anytime soon.

**Comment by piemonte** [comment]
📎 https://github.com/NextLevel/NextLevel/issues/39

**Comment by piemonte** [comment]
📎 https://github.com/NextLevel/NextLevel/issues/46
