### ISSUE TITLE
How can we integrate GPUImage2 

### ISSUE THREAD

**Issue by omarojo** [NextLevel/NextLevel#46]
Is there a way to integrate GPUImage2 with NextLevel, so that we have all the features of NextLevel, but the filtering processing is handled by GPUImage2.

**Comment by piemonte** [comment]
hey @omarojo nice question, thanks for the interest. i'm going to update the README with this info. i can't give you details on what components you use outside of this library, but I can explain the data flow from here.

**Comment by piemonte** [comment]
commit ceb0b150e6181351594cd0704b6ceaceabb22765
Author: patrick piemonte <patrick.piemonte@gmail.com>
Date:   Thu Feb 16 13:53:09 2017 -0800

    Update docs

commit f5cabcdd49a234b9d8ba4b0ebc650913e4c792f2
Author: patrick piemonte <patrick.piemonte@gmail.com>
Date:   Thu Feb 16 13:52:59 2017 -0800

    Add custom rendering instructions to README
