### ISSUE TITLE
Merging "External" Video with Original

### ISSUE THREAD

**Issue by Kareemarab** [NextLevel/NextLevel#47]
So I have a function that takes in a video and returns the same video but in reverse. How can I record a video using NextLevel, input it into my reverse() function, then merge the original and reverse video together so that they become one final video? I was going to use the add(Clip: ) method but it required a NextLevelClip type which I am not familiar on how to convert to.

**Comment by piemonte** [comment]
hey @Kareemarab 

when you're done capturing take the copied result of your reverse function and create a `NextLevelClip` with the file URL.  Then take that clip and add it to your `NextLevel.shared.session`. Then use


from there you create an `AVAssetExportSession` and give it those files to join. You can follow
