### ISSUE TITLE
🛠 NextLevel enhancements

### ISSUE THREAD

**Issue by piemonte** [NextLevel/NextLevel#5]
- [x] add improved authorization checks
- [x] custom output directory
- [x] AV session interruption recovery support
- [x] add better error reporting
- [x] `videoConfiguration` could have pre-defined sizing presets

**Comment by donpark** [comment]
Feature suggestions:

- [ ] support cancel (remove all clips & close session)
- [ ] support retake (all or just last clip)
- [ ] rich AVVideoCompositionCoreAnimationTool support

last one may be an exporter feature.

**Comment by piemonte** [comment]
hey @donpark. you're first two requests are already supported by calling funcs directly on the session.

can send you a couple notes when i get back to a computer.

**Comment by donpark** [comment]
I know. I implemented them already using methods you mentioned although I had to add some completion handlers to ensure changes are made serially. Just thought you might want to surface them via explicit API methods.

While implementing those features, I realized mergeClips wasn't removing the clips (mostly importantly their files) so it was an overall a good discovery experience.

**Comment by piemonte** [comment]
Ah, nice ideas. So you're suggesting adding completion handlers for 'NextLevelSession.removeLastClip' and 'NextLevelSession.removeAllClips'?

I had thought about updating mergeClips such that it removes them on completion but it was a destructive action that some apps may to want to occur, so I'll just add a line to the sample project shows how you can remove the clips after capture.

thanks for all the feedback! ✌️
