### ISSUE TITLE
Podfile not installing - tried with 0.3.3 - same error also

### ISSUE THREAD

**Issue by DaveInTO** [NextLevel/NextLevel#50]
[!] Unable to satisfy the following requirements:

- `NextLevel (~> 0.3.4)` required by `Podfile`

Specs satisfying the `NextLevel (~> 0.3.4)` dependency were found, but they required a higher minimum deployment target.

**Comment by piemonte** [comment]
Hey @DaveInTO thanks for the interest in the project. i'm guessing your deployment target is iOS 9, currently this project is setup for iOS 10 and after. I've had several folks ask for iOS 9 support, which is mostly some photography API support but I haven't had the time to do this.

📎 https://github.com/NextLevel/NextLevel/issues/7

**Comment by DaveInTO** [comment]
IOS10 works for me - super -you might just want to include that in the pods instructions.
Thanks!

**Comment by otymartin** [comment]
@piemonte would appreciate iOS 9 support.

**Comment by BhavinBhadani** [comment]
@DaveInTO can you tell me changes how it supports in iOS 10.0 ??
