### ISSUE TITLE
Orientation

### ISSUE THREAD

**Issue by DaveInTO** [NextLevel/NextLevel#51]
Do i have to do anything special to ensure the orientation is correct?
I start the app in portrait, rotate the phone to landscape.. Hit record, but continue to get 
Rotation: 0 in the resulting file.

 exiftool -Rotation 1488148498200.mp4 
Rotation                        : 0

**Comment by piemonte** [comment]
https://github.com/NextLevel/NextLevel/blob/0.3.4/Sources/NextLevel.swift#L609-L610

You can find the docs here too, https://nextlevel.github.io/NextLevel/
