### ISSUE TITLE
Cocoapods issue

### ISSUE THREAD

**Issue by serhii-londar** [NextLevel/NextLevel#52]
I tried to install NextLevev via cocoapods but get this error:

Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `NextLevel (~> 0.3.4)` required by `Podfile`

Specs satisfying the `NextLevel (~> 0.3.4)` dependency were found, but they required a higher minimum deployment target.

**Comment by piemonte** [comment]
hey @serhii-londar thanks for interest in the project. a few folks have encountered this, you need a deployment target of iOS 10. check out these issues:

📎 https://github.com/NextLevel/NextLevel/issues/50
📎 https://github.com/NextLevel/NextLevel/issues/7

**Comment by serhii-londar** [comment]
Thanks for your reply!
