### ISSUE TITLE
The flashMode property doesn't work

### ISSUE THREAD

**Issue by PaulAbrudan** [NextLevel/NextLevel#53]
I'm pretty new with the AVFoundation apis so I know I might be wrong, but here goes.

The flashMode setter performs an `AVCaptureDevice` `lockForConfiguration()` / `unlockForConfiguration()` which I believe can be removed since Apple deprecated the `flashMode` property and it's never set anyway. 

Also I think the flash problem is caused because the `flashMode` is never passed on to the `AVCapturePhotoSettings` before capture. I managed to fix it locally by adding `photoSettings.flashMode = self.photoConfiguration.flashMode` before the capture photo call. The cleaner way would have been to add it as an entry to the `avcaptureDictionary()` function on the `NextLevelPhotoConfiguration` but I was unable to find the corresponding key in the Apple Docs.

P.S. Thanks for the great library!

**Comment by piemonte** [comment]
hey @PaulAbrudan thanks for interest in the project. good catch with the setting, i missed that. ✌️

**Comment by PaulAbrudan** [comment]
Thank you for the library, I really enjoy using it! 👍🏻
