### ISSUE TITLE
Recording without Audio

### ISSUE THREAD

**Issue by sheharyar-rr** [NextLevel/NextLevel#55]
I noticed that I keep getting the issue "NextLevel, failed to start camera session" when I tried initialize without authorizing and setting up Audio Configuration. I don't use audio while recording video in my app, is there a way to not require Audio?

**Comment by piemonte** [comment]
hey @sheharyar-rr i haven't tested that but there's no reason why it shouldn't. might require a couple modifications.

**Comment by AntonReality** [comment]
@sheharyar-rr @piemonte faced the same issue. I don't need to record audio, but there's a permission check: 
`internal func authorizationStatusForCurrentCameraMode() -> NextLevelAuthorizationStatus {
        switch self.captureMode {
        case .audio:
            return self.authorizationStatus(forMediaType: AVMediaTypeAudio)
        case .video:
            let audioStatus = self.authorizationStatus(forMediaType: AVMediaTypeAudio)
            let videoStatus = self.authorizationStatus(forMediaType: AVMediaTypeVideo)
            return (audioStatus == .authorized && videoStatus == .authorized) ? .authorized : .notAuthorized
        case .photo:
            return self.authorizationStatus(forMediaType: AVMediaTypeVideo)
        }
    }`

If you're recording video you are forced to request for audio permission.

@piemonte should i upload a pull request for audio be optional?

**Comment by piemonte** [comment]
hey @AntonReality that'd be super helpful. ✌️

**Comment by piemonte** [comment]
https://github.com/NextLevel/NextLevel/pull/64
