### ISSUE TITLE
Clips are cut off when merging

### ISSUE THREAD

**Issue by edjiang** [NextLevel/NextLevel#58]
Hey @piemonte, thanks for the great library. I've been trying out the demo project as well as implementing in my own app, and noticed when merging multiple clips, they seem to be cutting the original short. Any idea why that might be?

This happens when merging, and in the demo project. I looked at the raw files saved in `/tmp` and it seems like every individual clip is being trimmed for some reason. 

I'm using this on Xcode 8.3 Beta 4, on an iPhone 6s with iOS 10.3

**Comment by piemonte** [comment]
hey @edjiang thanks for the inquiry. i haven't encountered this myself, so i have a couple questions for you. any chance you could confirm it or experienced it happening on release software? when a clip is cut off, is it always at the beginning or end or both? is the cut-off duration always the same length?

**Comment by edjiang** [comment]
Thanks Piemonte. I'll try doing a build in release mode; otherwise do you know which apps on the App Store are using this library? I can try downloading one to see. 

I can also run some more specific tests tomorrow to get more results.

Glad to see it's just me; could just be my beta software causing issues :)
