### ISSUE TITLE
Problem with CocoaPods

### ISSUE THREAD

**Issue by Kareemarab** [NextLevel/NextLevel#6]
I'm having trouble installing through CocoaPods. I'm receiving this error: 
            
    [!] Unable to satisfy the following requirements:
   
     - `NextLevel (~> 0.0.1)` required by `Podfile`

Any idea what might be going wrong? Thanks.

**Comment by piemonte** [comment]
hey @Kareemarab the release is tagged `0.0.1-beta.1`

i'm setting this up as a pod in project too – will let you know if anything else is needed

**Comment by Kareemarab** [comment]
Perfect. Thank you so much for this great work!

**Comment by piemonte** [comment]
no problem ✌️ 

don't thank me yet, this is brand new and i'm sure there's a ton of bugs.

**Comment by piemonte** [comment]
submitted a beta.2 because there were a couple pod integration bugs
