### ISSUE TITLE
Can I use with OpenCV2?

### ISSUE THREAD

**Issue by RafaelPlantard** [NextLevel/NextLevel#61]
Is it possible use with [OpenCV2 iOS Pack](http://opencv.org/releases.html).

**Comment by piemonte** [comment]
Hey @RafaelPlantard yes, it's possible to do so but I can't provide sample code for that at this time.

**Comment by RafaelPlantard** [comment]
Thanks @piemonte, I unfortunately make all my work without `NextLevel`.
