### ISSUE TITLE
NextLevel, session failed to append video frame to clip

### ISSUE THREAD

**Issue by RafaelPlantard** [NextLevel/NextLevel#62]
How can I solve it:
https://github.com/NextLevel/NextLevel/blob/master/Sources/NextLevelSession.swift#L396?

**Comment by egabor** [comment]
I have experienced this issue too. Any idea how to solve it?

**Comment by piemonte** [comment]
thanks for creating an issue. i've encountered this too. i'll have to get back to you on solutions.

**Comment by cemaleker** [comment]
I found out that calling `session?.reset()` during a recording session causes this error.

**Comment by bennnjamin** [comment]
In playing around with the example code, it appears this is related to pausing a session and trying to interact with the clip before the framework is done with processing the clip. If you use `pause(withCompletionHandler: completionHandler)`(https://github.com/NextLevel/NextLevel/blob/master/Sources/NextLevel.swift#L2180) and do any operations on the clip in your closure it seems to work fine.

Interestingly enough, I tried access `NextLevel.shared.session.url` immediately after a `NextLevel.shared.pause()` and get a valid URL however trying to save it fails. Also `NextLevel.shared.session.clips.count` is still `0`.

**Comment by codepushr** [comment]
Just included this into a sample app. Got the same error, not sure how to resolve it.

```
import CoreMedia
import AVKit
import NextLevel

class MyViewController: UIViewController, NextLevelVideoDelegate {
    ...
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.previewView.backgroundColor = UIColor.black
        NextLevel.shared.previewLayer.frame = previewView.bounds
        previewView.layer.addSublayer(NextLevel.shared.previewLayer)
    
        NextLevel.shared.videoDelegate = self
        
        NextLevel.shared.videoConfiguration.maximumCaptureDuration = CMTimeMakeWithSeconds(5, 600)
        NextLevel.shared.audioConfiguration.bitRate = 44000
    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        try! NextLevel.shared.start()
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        
        NextLevel.shared.stop()
    }

    @IBAction func captureAction(_ sender: Any) {
        if !self.capturing {
            NextLevel.shared.record()
            self.capturing = true
        } else {
            NextLevel.shared.stop()
            self.capturing = false
        }
    }
    ...
    // Delegates ...
}
```

**Comment by geowarsong** [comment]
Is there any news regarding this issue?

**Comment by natan** [comment]
This appears to only happen when you start recording less than ~2 seconds after `nextLevelSessionDidStart` is invoked. If you delay recording until after then, there is no issue. I spoke with @piemonte about this and investigated for a while, and there's no immediate internal fix obvious, but for now you can add in a delay between those two events to avoid this failure.

**Comment by rockar06** [comment]
I faced this issue too, I couldn't save any videos.
I used this code to save the record: 
```swift
func endCapture() {
    if let lastClipUrl = NextLevel.shared.session?.lastClipUrl {
        self.saveVideo(withURL: lastClipUrl)
    } else {
        // prompt that the video has been saved
        let alertController = UIAlertController(title: "Video Capture", message: "Not enough video captured!", preferredStyle: .alert)
        let okAction = UIAlertAction(title: "OK", style: .default, handler: nil)
        alertController.addAction(okAction)
        self.present(alertController, animated: true, completion: nil)
    }
}
```
but it always fail to save video because `lastClipUrl` was `nil`, so I decide to use the `endClip` function from `NextLevel.shared.session`:

```swift
func endCapture() {
    NextLevel.shared.session?.endClip(completionHandler: { (clip, error) in
        if error == nil {
            self.saveVideo(withURL: (clip?.url)!)
        } else {
            print("Error saving video: \(error?.localizedDescription ?? "")")
        }
    })
}
```
In this way, I can save the video pressing start/stop button without problems.

**Comment by natan** [comment]
For those following along: the [workaround above involving an artificial start delay](https://github.com/NextLevel/NextLevel/issues/62#issuecomment-372795544) did not fix this issue on all iOS devices. Unfortunately I couldn't come up with a proper correct fix for this in NextLevel, so I ended up replacing our usage of NextLevel with a `AVCaptureMovieFileOutput` based solution, which nicely [provides a delegate method](https://developer.apple.com/documentation/avfoundation/avcapturefileoutputrecordingdelegate/1387301-fileoutput) for when the file recording has started. Hope that helps those that have run into this issue.

**Comment by natan** [comment]
@piemonte Yeah that could work! I'm actually doing back to back clips with a single `AVCaptureMovieFileOutput` (ie. `startRecording()` → `stopRecording()` → `startRecording()` → `stopRecording()`) and it is working well.

**Comment by piemonte** [comment]
@natan 738a2e747720650244d41c2087a80d605ef5e479

don't have time to do this right now but got it started
