### ISSUE TITLE
Starting a new video

### ISSUE THREAD

**Issue by egabor** [NextLevel/NextLevel#63]
How can I remove the clips from the session that I've been recorded previously? 
Stopping the current session and starting a new is a possible solution, but it's very slow.
Is there a simplier solution?

**Comment by piemonte** [comment]
hey @egabor thanks for the inquiry. before merging, you can use the methods on session to re-arrange or modify clips.

https://github.com/NextLevel/NextLevel/blob/master/Sources/NextLevelSession.swift#L577-L605

so, nextLevel.shared.session.remove(...
