### ISSUE TITLE
pod install problem with target ios9.0

### ISSUE THREAD

**Issue by BhavinBhadani** [NextLevel/NextLevel#69]
I am try to add dependency in my podfile with deployment target 9.0 but I received this error.

```
[!] Unable to satisfy the following requirements:

- `NextLevel (~> 0.3.5)` required by `Podfile`

Specs satisfying the `NextLevel (~> 0.3.5)` dependency were found, but they required a higher minimum deployment target.
```

So what is the minimum deployment target? and is it any support for iOS 9.0 ??

**Comment by piemonte** [comment]
hey @BhavinBhadani, see #50 

📎 https://github.com/NextLevel/NextLevel/issues/50
