### ISSUE TITLE
iOS 9 support

### ISSUE THREAD

**Issue by pilot34** [NextLevel/NextLevel#7]
Hello!

Have you got plans to support iOS 9? There is iOS 10 only in podspec now.

**Comment by piemonte** [comment]
hey @pilot34, unfortunately only 10 and forward. Just don't have the time for that type of support. Thanks for the idea.

**Comment by miken01** [comment]
Hi, is there any specific reason, other than time constraints, you aren't supporting iOS 9? Such as using API methods that are new to iOS 10 that have no iOS 9 variant? Just curious how difficult it would be to fork your project and add support for iOS 9. Considering iOS 9 still has about 15% marketshare it's pretty unlikely many people will adopt your library for production products.

**Comment by jonandersen** [comment]
@miken01 It's related to the new iOS 10 api: https://developer.apple.com/reference/avfoundation/avcapturedevicetype
