### ISSUE TITLE
Cannot switch between Photo and Video Capture mode

### ISSUE THREAD

**Issue by bennnjamin** [NextLevel/NextLevel#72]
I've got a button setup to toggle between photo and video mode like the iOS camera app. I am toggling by having my button's action set `NextLevel.shared.captureMode = NextLevelCaptureMode.photo` or `NextLevel.shared.captureMode = NextLevelCaptureMode.video` accordingly. 

When you toggle from photo and back to video, there is no error or crash but the UI becomes completely unresponsive/frozen. Furthermore, this operation blocks the main thread for a few seconds.

**Comment by normanholz** [comment]
@bennnjamin I am having the same problem. Is there any information on how to properly switch between capture modes?

**Comment by piemonte** [comment]
hey @bennnjamin @normanholz not sure what type of photo capture you're looking to build but the discussion here on the various types may be helpful:

https://github.com/NextLevel/NextLevel/issues/79#issuecomment-305572067

there is a delay when switching modes that comes from the device hardware itself which makes the video frame capture for photos so appealing.

**Comment by bennnjamin** [comment]
@piemonte I originally closed this issue because I discovered that myself...unfortunately I'm not using the library in my project because of other issues. I was interested in real-time filtering but it didn't seem this library nor PBJ vision could support text overlay on both a camera preview and burning it into the recording itself.

**Comment by normanholz** [comment]
@piemonte @bennnjamin I want to be able to switch modes because image quality in photo mode is superior to the video frame capture, isn't it? 

For anyone interested, the crash/freeze on switching modes occurs when NextLevel is configured to `automaticallyConfiguresApplicationAudioSession = false`, which one might want to set to allow background audio while recording.
