### ISSUE TITLE
Flip Camera Merge Clip error

### ISSUE THREAD

**Issue by jinksmysteryman** [NextLevel/NextLevel#75]
In my camera view controller, I have a button that flips the camera when a button is pressed by calling `NextLevel.shared.flipCaptureDevicePosition()`

However, when I finish recording and try to merge the clips in the session with `NextLevel.shared.session?.mergeClips`, the clip right after the camera switch is replaced with the first clip. For example, if I have a recording session like (front camera: Clip 1, Clip2, switch to back camera: Clip 3), the resulting file will be Clip 1, Clip2, Clip1. 

Any ideas what the issue might be? Thanks for the help.

**Comment by captainuberawesome** [comment]
@piemonte found the cause of this issue - `reset()` is called on a `NextLevelSession` object when the camera is flipped (when updateVideoOrientation() is called). It resets `_clipFilenameCount` of the session back to 0 so all subsequently captured clips have the wrong url. Removing the line `self._clipFilenameCount = 0` from `reset()` fixes the issue.

**Comment by piemonte** [comment]
@captainuberawesome thanks for the research! i'll land something today. awesome username too. ✌️

**Comment by NirajCapermint** [comment]
Flipping the camera showing black screen for 1-2 seconds, any idea?
