### ISSUE TITLE
AVCaptureSession is started on the main thread

### ISSUE THREAD

**Issue by PaulAbrudan** [NextLevel/NextLevel#76]
<img width="863" alt="screen shot 2017-05-22 at 22 15 01" src="https://cloud.githubusercontent.com/assets/5418161/26339345/2db96e46-3f3c-11e7-8a48-7cbc4d5d253b.png">

AVCaptureSession `startRunning()` on the main thread is discouraged by Apple in the docs (https://developer.apple.com/reference/avfoundation/avcapturesession)

Even though there is a serial queue in play Apple optimizes the sync call executing the block on the calling thread "when possible". (Based on: https://developer.apple.com/reference/dispatch/dispatchqueue/1452870-sync)

A comment in the source file suggests that the sync call is required for a device availability
(`// Note: sync is required on start in order to ensure a device is available for configuration`) so maybe only wrapping the actual `startRunning()` function call in an async block would be a suitable solution?

I have raised this as an issue because I believe this causes my current view controller setup to sometimes not initialize properly (not even calling `viewDidLoad()`) and freeze. It is so sporadic that I smell thread related trouble - and after ~1 week of investigation I might have just found my culprit - at least I hope so xD

If this is by design and something evades my understanding of the library I apologize to have raised it as an issue.

Thanks again for your awesome contribution!

**Comment by piemonte** [comment]
hey @PaulAbrudan – i really appreciate the good research and comments. i'll investigate and get this resolved.

**Comment by PaulAbrudan** [comment]
@piemonte thanks for the response. If you have time, could you please explain to me the reason for using the sync call? I'm trying to wrap my head around the comment: `// Note: sync is required on start in order to ensure a device is available for configuration`.

**Comment by ffittschen** [comment]
For us the symptom were timeouts of UI Tests. I also tracked these timeouts down to this issue. It seems like starting the session takes multiple seconds on the simulator whereas starting the session on a real device is way shorter.

**Comment by piemonte** [comment]
hey @PaulAbrudan what i meant by the comment was that we need to either provide a means to pass in a closure or use a delegate method for "post-start" configuration. so configuration changes that require the existence of a device, like time scale or format. once was setup just wasn't using it properly and for some reason was using a sync instead. pushed to master, let me know if this works out okay.

**Comment by PaulAbrudan** [comment]
@piemonte sorry for only getting back to you now, I've had a crazy couple of days. The proposed fix works as expected, thank you!
