### ISSUE TITLE
Slow Motion Example?

### ISSUE THREAD

**Issue by tonymuu** [NextLevel/NextLevel#77]
Hi guys, really awesome project! I want to achieve slow motion video recording in the app I am working on. I was able to "stretch out" the video with AVFoundation only, but the quality sucked because the frame rate was unchanged while timescale was decreased. I saw that NextLevel supports slow motion recording on supported device, so I tried to look into the documentations and only found the `bitrate` and `frameRate` property. How should I use them to achieve slow motion video recording? Thanks!

**Comment by tonymuu** [comment]
The `frameRate` property of the `NextLevel.shared` instance started with 0... so I wasn't sure what value to set it to in the first place..

**Comment by jesseorg** [comment]
I am also trying to get the camera to run at high speed, 240 Hz. Looking through the NL code it seems that the frameRate can be set arbitrarily via NextLevel.shared, and then code in set{} will set the camera to the closest requested framerate. However when I set nextLevel.frameRate = 120 or another number, set{} is never accomplished because " if let device: AVCaptureDevice = self._currentDevice" returns false, on line 1864 of NextLevel.swift

**Comment by piemonte** [comment]
hey @tonymuu @jesseorg you have to ensure the session is started before specifying the frameRate.

```
        let nextLevel = NextLevel.shared
        if PermissionsViewController.shouldPresentPermissionsIfNecessary() == false {
            do {
                try nextLevel.start()
                
                // update active device configuration
                nextLevel.updateDeviceFormat(withFrameRate: CMTimeScale(30), dimensions: CMVideoDimensions(width: 1280, height: 720))
//...
          ```

**Comment by jesseorg** [comment]
Thank you @piemonte !  

@tonymuu The above can be added to func "viewWillAppear"

**Comment by tonymuu** [comment]
Very nice! I will try it out today. Thank you

**Comment by tonymuu** [comment]
@piemonte @jesseorg the code above worked out great! Thank you so much!!

**Comment by piemonte** [comment]
👍

**Comment by SparkMultiz** [comment]
Hello Guys , I have used this project and it's really good... can you please help me to export slow/fast motion video.
