### ISSUE TITLE
Low Quality Video Capture

### ISSUE THREAD

**Issue by otymartin** [NextLevel/NextLevel#83]
@piemonte 
Hey the previous issue #34  was closed so I thought it necessary to bring this up again since i failed to fix it.

For whatever reason despite setting videoConfigured to high quality, I still get lowQuality output video when I play back using your other library Player.

I have these settings in my viewDidLoad so would appreciate further hints as to what could possible cause the bad video. Im using the latest version of this library.
```swift
self.nextLevel.delegate = self
        self.nextLevel.videoDelegate = self
        self.nextLevel.photoDelegate = self
        self.nextLevel.deviceDelegate = self
        self.nextLevel.captureMode = .video
        self.nextLevel.focusMode = .autoFocus
        self.nextLevel.devicePosition = .front
        self.nextLevel.deviceOrientation = .portrait
        self.nextLevel.videoStabilizationMode = .auto
        self.nextLevel.videoConfiguration.bitRate = 2000000
        self.nextLevel.videoConfiguration.preset = AVCaptureSessionPresetHigh
        self.nextLevel.videoConfiguration.transform = CGAffineTransform(scaleX: -1, y: 1)```

**Comment by piemonte** [comment]
hey @otymartin thanks, will check this out when i get a chance

**Comment by yazeedabalkhail** [comment]
Hello there!

Was wondering if any update has happened on this, or if you found a workaround? Experiencing the same issue.

@otymartin @piemonte

**Comment by yazeedabalkhail** [comment]
If it is any help with helping debugging the problem, here are a couple of test i did on different presets:

1- When using presets low or medium --> You get the same results as when filming
2- When using presets high or hd etc --> You get pixelated, however the first second of displaying the video will not be pixelated
3- When using preset hd4K3840x2160 --> You get pixelated, however it is the lesser of all high preset options such as hd720, etc. Although still noticable
4- When using preset iFrame960x540 --> You get a video better then medium quality, without the pixelation happening

Hope this can help, thank you.

**Comment by otymartin** [comment]
@yazeedabalkhail no had to use another lib. Would love to use this lib though so will come back to it and take on this issue again and see if i can figure it out.

**Comment by BrikerMan** [comment]
I have the similar issue, is there any ways to improve video quality.

**Comment by otymartin** [comment]
@klpl what did you increase it to?

**Comment by klpl** [comment]
the value I used was based on Apple's sample code: https://developer.apple.com/library/content/samplecode/RosyWriter/Listings/Classes_Utilities_MovieRecorder_m.html#//apple_ref/doc/uid/DTS40011110-Classes_Utilities_MovieRecorder_m-DontLinkElementID_23

`bitsPerSecond = numPixels * bitsPerPixel;`

**Comment by otymartin** [comment]
@klpl cool man, will try it out and see if this finally solves it.

**Comment by tungfam** [comment]
@klpl hi, could you please kindly share the code how you calculate `bitsPerSecond`?
from apple's [docs] (https://developer.apple.com/library/content/samplecode/RosyWriter/Listings/Classes_Utilities_MovieRecorder_m.html#//apple_ref/doc/uid/DTS40011110-Classes_Utilities_MovieRecorder_m-DontLinkElementID_23) it seems we need this:
`CMVideoDimensions dimensions = CMVideoFormatDescriptionGetDimensions( videoFormatDescription )` to calculate it. But where can we get it from ? 😅 

Will appreciate any help!

**Comment by klpl** [comment]
@tungfam
In NextLevelConfiguration.swift > avcaptureSettingsDictionary method: 
`let numPixels = (config[AVVideoWidthKey] as! Int) * (config[AVVideoHeightKey] as! Int)`
 `let bitsPerPixel = 10.1`
`let bitsPerSecond = Int(Double(numPixels) * bitsPerPixel)`
[...]
`compressionDict[AVVideoAverageBitRateKey] = NSNumber(integerLiteral: bitsPerSecond)`

**Comment by tungfam** [comment]
many thanks to @klpl I found out what fixes the issue and created a [PR](https://github.com/NextLevel/NextLevel/pull/123).

More details:

after few hours of testing and going around the code, I found out that no matter what value you set to `NextLevel.shared.videoConfiguration.bitRate` either `1` or `999999999` it will not affect the video quality.

then I applied the code that @klpl suggested. And checked again that changing `NextLevel.shared.videoConfiguration.bitRate` doesn't affect anything. But the video quality did become better.

Then I changed `videoConfiguration.preset` to `.high` or to `.hd4K3840x2160` and the quality was just amazing 👌 .

@yazeedabalkhail thank you too!:) I was trying to use `iFrame960x540` which was actually good (before I applied changes from PR). But then after fixing the issue the `.high` was better than `iFrame960x540`.

@piemonte first of all thanks a lot for a such cool lib!
please take a chance to review the [PR](https://github.com/NextLevel/NextLevel/pull/123).
Try testing it and you will see how better the video quality became. Please let me know if you have questions.

**Comment by piemonte** [comment]
i added a better configuration to the sample project, hope that helps everyone.

050ba1bb1f078a12a41a22d2dda057f87765068b
