### ISSUE TITLE
Fix compile error in Xcode 9 beta 4

### ISSUE THREAD

**Issue by hmazelier** [NextLevel/NextLevel#88]
Hi Piemonte ! 
First of all, thanks for this framework and your fabulous previous work on PBJVision ! 
I fixed a compile error appearing since beta 4 of xcode 9 (was not the case with xcode 9 beta 3) .
Really small fixes, here is the forked repo: https://github.com/hmazelier/NextLevel ;
If you want me to do a PR, let me know ! 
Have a great one

**Comment by piemonte** [comment]
hey @hmazelier thanks for the good words! ✌️ 

let's wait until we're in final beta before making these changes. i also need to update the `swift-4` branch too.

**Comment by hmazelier** [comment]
Fine sir !
Let me know if I can be useful,

Best
