### ISSUE TITLE
`didStartClipInSession` called multiple times while the camera is running

### ISSUE THREAD

**Issue by slash7** [NextLevel/NextLevel#9]
While the camera is running the `didStartClipInSession` is called continually.

```
    func nextLevel(_ nextLevel: NextLevel, didStartClipInSession session: NextLevelSession) {
        print("Did start clip")
    }
```

When I pause the `clip.asset` and `session.asset` are `nil`.
```
func start() {
     NextLevel.sharedInstance.record()
}

func pause() {
     NextLevel.sharedInstance.pause()
}

func nextLevel(_ nextLevel: NextLevel, didCompleteClip clip: NextLevelClip, inSession session: NextLevelSession) {
        print(clip.asset)
        print(session.asset)
    }
```
I was expecting access to the asset in this method to be able to export it.

**Comment by piemonte** [comment]
hey @slash7 apologies and thanks for the issues. landed several commits that address the nil assets and delegate improper callbacks. didStartClipInSession does get called more often than expected, but it should be improved a long with the core functionality. please let me know if things work properly for you and can close this.

commit 551314d44460dabe22a8938326cb3f7d693c73d4
Author: patrick piemonte <piemonte@alumni.cmu.edu>
Date:   Sun Oct 9 23:35:43 2016 -0700

    NextLevelClip, ensure assets are properly allocated when the URL is set

commit afaead21a5199949433e5e1903d74023c588f73f
Author: patrick piemonte <piemonte@alumni.cmu.edu>
Date:   Sun Oct 9 23:24:04 2016 -0700

    NextLevel, fix initial recording state issues with new clips

**Comment by slash7** [comment]
hi @piemonte , thanks for the quick fixes, things work properly now.
