### ISSUE TITLE
Reconfigure on each focus and exposure change

### ISSUE THREAD

**Issue by NikolayGenov** [NextLevel/NextLevel#92]
Hey there,
Awesome library, but can we make it even better ? 
I was wondering for few things that might or might not be problems:

- Does this `device.isSubjectAreaChangeMonitoringEnabled = true`
have to change on each `focusEnded` and `exposureEnded` call?
https://github.com/NextLevel/NextLevel/blob/9cad174578d1986d2cecc6c230de79666764bebe/Sources/NextLevel.swift#L1663-L1691

- Another thing I've found that I can't explain to myself is why the following:
Why is `device.isAdjustingFocus` **always** `false` in here
https://github.com/NextLevel/NextLevel/blob/9cad174578d1986d2cecc6c230de79666764bebe/Sources/NextLevel.swift#L1611-L1624

- And finally: Why is `focusAtAdjustedPointOfInterest` being called instead of `focusExposeAndAdjustWhiteBalance`  in the function above?

**Comment by NikolayGenov** [comment]
@piemonte ?

**Comment by piemonte** [comment]
hey @NikolayGenov thanks for the project interest and good words.

in your first question, subject change monitoring is always enabled for auto-focus to re-initiate focus.

your second question may be a bug.

your third question, auto adjusting white balance at this frequency produces over contrast at times. this actually closely matches the behavior of the default camera application.

**Comment by NikolayGenov** [comment]
@piemonte 
For the first question: yes, it's enabled but it's it is being configured on each of those calls:
Let say `focusEnded` is called and it is not adjusting focus anymore, so it does beyond the guard. 
Next the device is currently on . continuousAutoFocus so it goes in the if and the device is locked for configuration, the property `device.isSubjectAreaChangeMonitoringEnabled` is being set to true EVERY time this happens. Is that desirable behavior? I mean should be set only once and not set each time ? 
Same goes to `focusAtAdjustedPointOfInterest`. If the device is not adjusting anything anymore and something moves, does it mean we have to reset the point to be in the middle again? I mean we should have set it only once and it remembers right ?

**Comment by piemonte** [comment]
hey @NikolayGenov, are you asking because you're experiencing un-expected behavior? if so, can you share that behavior and then expected result?

yes, resetting the point to middle again if the scene changes is desired.

**Comment by NikolayGenov** [comment]
Hey @piemonte 
Okay, let's discuss the whole point thing about `focusEnded`. (and related things)
It's being called from KVO so the user should be notified when the event has finished and so it can rely on that behavior is being passed from the default, just wrapped in a delegate.
What is happening now is for example the method is called, then it is check if the focus is stillAdjusting - meaning that the other one - `focusStarted` was being called (or even before that). That seems like you are trying to aggregate and notify the user when the focus is really ended and a new one is not started, but I think that's somewhat misleading.

Then you are checking if it's in autofocus mode, and if it is, you are changing the properties on the device, which most likely was set somewhere else, and it isn't it should be. I don't thing that method should at any point set that property `isSubjectAreaChangeMonitoringEnabled`. If it's true it should stay true, if it false it should stay false. 

And at the end DidStopFocus is eventually called. I think this should be the only thing called in this method, just like focusStated method. 

Absolutely the same applies to `exposureEnded`

**Comment by piemonte** [comment]
@NikolayGenov that make sense, i appreciate the details. if you create a single PR will your changes, i'll test and verify. ✌️

**Comment by NikolayGenov** [comment]
Will do, but at some point later today or tomorrow :)

**Comment by piemonte** [comment]
hey @NikolayGenov not sure if you ever had the opportunity to share a fork. let me know if you ever come back to this and we can re-open.
