### ISSUE TITLE
Audio isn't present.

### ISSUE THREAD

**Issue by HackShitUp** [NextLevel/NextLevel#93]
After the following method is called when a gesture recognizer ends:
`NextLevel.shared.pause()`

The video is exported in the NextLevel Video Delegate Method like so:

`    func nextLevel(_ nextLevel: NextLevel, didCompleteClip clip: NextLevelClip, inSession session: NextLevelSession) {
        // Export recorded video...
        session.mergeClips(usingPreset: AVAssetExportPresetHighestQuality, completionHandler: { (url: URL?, error: Error?) in
            if let _ = url {
                /// PASS recorded video...
                let capturedVC = self.storyboard?.instantiateViewController(withIdentifier: "capturedVC") as! Captured
                capturedVC.recordedURL = url
                self.navigationController?.pushViewController(capturedVC, animated: true)
            } else if let _ = error {
                print(error?.localizedDescription as Any)
            }
        })
    }`

But for some reason, I can't hear the audio....

**Comment by bdering** [comment]
Any updates here? Have encountered the same issue.

**Comment by HackShitUp** [comment]
@bdering I decided to make my own camera using GPUImage.
