### ISSUE TITLE
It is not possible to remove the clip by "removeAllClips" when a flag "removeFiles" is false

### ISSUE THREAD

**Issue by SivinNikita** [NextLevel/NextLevel#96]
self._clips.removeFirst() called in condition "if removeFiles {...}"
https://github.com/NextLevel/NextLevel/blob/9cad174578d1986d2cecc6c230de79666764bebe/Sources/NextLevelSession.swift#L606-L618

**Comment by piemonte** [comment]
good catch @SivinNikita ✌️
