### ISSUE TITLE
iOS 11 support for depth data and camera intrinsics

### ISSUE THREAD

**Issue by piemonte** [NextLevel/NextLevel#98]
iOS 11 support for depth data and camera intrinsics

**Comment by piemonte** [comment]
it's possible to receive this information in ARKit mode, but would be nice to support the AVFoundation/CMSampleBuffer means as well.

**Comment by otymartin** [comment]
@piemonte
Is this coming out soon with iphone x launch upon us? I have a few use cases & would love to see this happen.

**Comment by piemonte** [comment]
hey @otymartin i haven't had much free time to add this but it'd be nice to have.

i think it could even just be a simple CMSampleBuffer extension. feel free to contribute if you've already done this.
