### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by PaulAbrudan** [NextLevel/NextLevel#99]
Hi, I'm getting this weird error while trying to integrate the Swift 4 version of NextLevel (I'm using Xcode 9 GM.):

`Undefined symbols for architecture arm64:
  "__T012AVFoundation37_AVCapturePhotoOutputSwiftNativeTypesPAAE19supportedFlashModesSaySo0B6DeviceC0I4ModeOGfg", referenced from:
      __T07WinkDev9NextLevelC9flashModeAA0cd5FlashF0Ofs in NextLevel.o
  "__T0So22AVCapturePhotoSettingsC12AVFoundation01_abC16SwiftNativeTypesACWP", referenced from:
      __T07WinkDev27NextLevelPhotoConfigurationC19avcaptureDictionarys0H0VySSypGSgyF in NextLevelConfiguration.o
  "__T0So20AVCapturePhotoOutputC12AVFoundation01_abC16SwiftNativeTypesACWP", referenced from:
      __T07WinkDev9NextLevelC9flashModeAA0cd5FlashF0Ofs in NextLevel.o
  "__T012AVFoundation39_AVCapturePhotoSettingsSwiftNativeTypesPAAE016availablePreviewc11PixelFormatG0Says6UInt32VGfg", referenced from:
      __T07WinkDev27NextLevelPhotoConfigurationC19avcaptureDictionarys0H0VySSypGSgyF in NextLevelConfiguration.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

I have tried both CocoaPods & directly in my project. Could you please enlighten me on what I am missing? Thanks!

**Comment by piemonte** [comment]
@PaulAbrudan hey, use `0.7.1` this was a bug with iOS 11 GM

https://forums.developer.apple.com/thread/86810

**Comment by PaulAbrudan** [comment]
Thanks a lot for the fix!
